### ISSUE TITLE
Index Coop mislabeled as Set protocol

### ISSUE THREAD

**Issue by ncitron** [DefiLlama/DefiLlama-Adapters#10]
It looks like my recent PR for an Index Coop adapter has been deployed on the UI, but labeled as the Set Protocol. The Index Coop is founded by the Set team, and is built on top of the protocol, but is distinct from Set and has a very different TVL. I can provide information about Index for the UI if needed.

**Comment by DefiLlama** [comment]
Hi, yes I spoke to Gabriel and he explained that should be corrected which I'll do now

**Comment by DefiLlama** [comment]
Can you confirm you currently don't have an audit?

**Comment by DefiLlama** [comment]
==> https://defillama.com/protocol/index-coop All okay?

**Comment by ncitron** [comment]
Index uses the Set Protocol contracts, which have been fully audited.
