### ISSUE TITLE
Change description for Autofarm

### ISSUE THREAD

**Issue by 0xsis** [DefiLlama/DefiLlama-Adapters#100]
The Autofarm ecosystem comprises of 3 main products; firstly, a cross-chain yield optimizer which automates yield farming for users, a DEX aggregator (AutoSwap) that provides users' with the best swap rates and an intelligent portfolio manager/ tracker (farmfolio). Vaults are live on both Binance Smart Chain (BSC) and Huobi ECO chain (HECO) with the other products set to go cross-chain soon.

**Comment by 0xngmi** [comment]
Done! Let me know if anything else needs to be changed
