### ISSUE TITLE
Listed on a wrong category

### ISSUE THREAD

**Issue by salimdev04** [DefiLlama/DefiLlama-Adapters#10087]
Hello guys, we have just integrated Defillama, but in a wrong category. The category should be Derivatives:
Dirac Finance is a DeFi protocol proposing yield strategies based on derivatives (it can be structured products, options, tokenized bonds, using perps for enhancing the yield and risk mitigation...), we plan to collaborate with Market Makers such as Aveo, who are in the Derivatives category. 

Can you please switch our current category from Options Vaults to Derivatives? 
Our link in Defillama: https://defillama.com/protocol/dirac-finance#information

Thanks

**Comment by g1nt0ki** [comment]
hi @salimdev04 "Derivatives" is meant for platform where users can trade derivatives, but that is not the case here right?

**Comment by g1nt0ki** [comment]
no, in aevo, I can trade perps, but dont see that option on your dapp
