### ISSUE TITLE
Listed in polkadot chains

### ISSUE THREAD

**Issue by killbond007** [DefiLlama/DefiLlama-Adapters#10120]
Hello DefiLlama , 
   We hope to list Bifrost into Polkadot instead of Kusama because the majority of our TVL is under Polkadot ( https://defillama.com/chains/Polkadot https://defillama.com/chains/Kusama)

**Comment by realdealshaman** [comment]
This was discussed within a group chat. Please provide a clear distinction within the adapters that calculate the TVL, showing the amounts for Polkadot and Kusama separately
