### ISSUE TITLE
Add MOBOX

### ISSUE THREAD

**Issue by oscarsiauw** [DefiLlama/DefiLlama-Adapters#1025]
https://www.mobox.io/home/#/iframe/momo

**Comment by 0xngmi** [comment]
pls PR or provide addresses

**Comment by oscarsiauw** [comment]
Address is https://www.mobox.io/home/#/iframe/momo
What other address you need?

**Comment by waynebruce0x** [comment]
https://github.com/DefiLlama/DefiLlama-Adapters/pull/1142
