### ISSUE TITLE
Add Sheesha Finance

### ISSUE THREAD

**Issue by oscarsiauw** [DefiLlama/DefiLlama-Adapters#1026]
https://www.sheeshafinance.io/

**Comment by 0xngmi** [comment]
pls PR or provide addresses

**Comment by oscarsiauw** [comment]
Address is https://www.sheeshafinance.io/
What other address do you need?

**Comment by waynebruce0x** [comment]
https://github.com/DefiLlama/DefiLlama-Adapters/pull/1142
