### ISSUE TITLE
sommelier finance. SL states TVL as $73m, but imo it should not include double counted TVL in the same protocol

### ISSUE THREAD

**Issue by g1nt0ki** [DefiLlama/DefiLlama-Adapters#10766]
For example, their Real Yield BTC product is generating yield with their Real Yield ETH vault under the hood. Therefore $1 in the BTC vault is counting as ~$2 w/ $1 going to the BTC vault and ~$1 going to the ETH vault

**Comment by 0xpeluche** [comment]
Hello, after checking the code of Sommelier, there is already an implementation of a Dedupe function that works by removing the base vaults that would be used by other vaults, such as the Real Yield BTC which uses the Real Yield ETH. For example, for the Real Yield BTC contract, we see in the contract that there is:

~$7.3M through the Real Yield ETH, which would give a total TVL in WETH on Ethereum of: WETH 53.92M if we did not deduct the value.
However, with the Dedupe function in place, we only have:

WETH 46.47M on Ethereum, which clearly marks the deduction of the Real Yield ETH that was in the Real Yield BTC, allowing each base vault to be counted only once, even if it is used by other vaults in parallel.
The TVLs displayed on the Sommelier site are exactly those found by Defillama

https://app.sommelier.finance/
