### ISSUE TITLE
Inverse Finance FiRM missing wstETH TVL

### ISSUE THREAD

**Issue by nourharidy** [DefiLlama/DefiLlama-Adapters#10800]
`inverse-finance-firm` project is missing all wstETH TVL despite the contracts being included in the adapter.

[DeFillama TVL](https://defillama.com/protocol/inverse-finance-firm): $14.3M
[FiRM TVL](https://www.inverse.finance/firm): $23M

Not sure why it's happening. Could be an issue due to both stETH and wstETH tokens being included in the same TVL where only stETH ended up being counted. Not sure.

**Comment by 0xpeluche** [comment]
Hello, after checking with the command:
`node test.js projects/inverse-finance-firm/index.js`

![image](https://github.com/DefiLlama/DefiLlama-Adapters/assets/110820448/a63c27fc-40ca-4b02-a286-fa0b2136d81f)

DL correctly retrieves the TVL displayed by https://www.inverse.finance/firm

![image](https://github.com/DefiLlama/DefiLlama-Adapters/assets/110820448/23b4c878-2cc6-4f3b-a304-13ed7d780b7d)

wstETH is correctly displayed.

**Comment by g1nt0ki** [comment]
@nourharidy ngmi looked into this, for some reason, one of the pool creation event was not cached and that led to missing tvl, this was fixed by resetting cache
