### ISSUE TITLE
EterThe adapter at projects/T2T2 exports TVL:

### ISSUE THREAD

**Issue by Armanbeyg** [DefiLlama/DefiLlama-Adapters#10818]
The adapter at projects/T2T2 exports TVL: 
        
 
 
    base                      20.77 k
    ethereum                  4.44 k
    
    total                    25.21 k

_Originally posted by @llamatester in https://github.com/DefiLlama/DefiLlama-Adapters/issues/8078#issuecomment-1811909810_

**Comment by realdealshaman** [comment]
Hey, it shows the same amount on the ui as from the adapter:
![image](https://github.com/DefiLlama/DefiLlama-Adapters/assets/85087525/227c9590-4b95-4dd5-9460-b5beb481aaf4)
