### ISSUE TITLE
Astherus should be Restaking category

### ISSUE THREAD

**Issue by langyoung** [DefiLlama/DefiLlama-Adapters#10913]
Hello, Astherus should be Restaking category, not Farm, would you please help to move to Restaking category? Thank you very much!
<img width="979" alt="image" src="https://github.com/DefiLlama/DefiLlama-Adapters/assets/174692398/9ee0b577-e449-4337-9f55-4dc1a22d46f2">
<img width="929" alt="image" src="https://github.com/DefiLlama/DefiLlama-Adapters/assets/174692398/6dc893d0-f186-4067-b84e-43a208ea515f">

**Comment by realdealshaman** [comment]
Hey @langyoung, thanks for raising this issue. Could you provide more details on how the LSTs are used within Astherus for restaking and securing networks? Is Eigenlayer being used in this process?

**Comment by langyoung** [comment]
> Hey @langyoung, thanks for raising this issue. Could you provide more details on how the LSTs are used within Astherus for restaking and securing networks? Is Eigenlayer being used in this process?

Currently we do not use LST Seucuring Network and eignlayer, we are a liquidity hub that can enrich LST utility, such as using LST as a margin for Perp trading or strategy trading, and in the future we support LST involved in Astherus Layer staking and governance.

**Comment by realdealshaman** [comment]
@langyoung thanks for the additional info, as is we currently can't add it to the Restaking category since that is specific to protocols that restake LSTs to secure other networks with them. What would be the main purpose users deposit into Astherus? is it to get a yield? if so we can change it to Yield category instead

**Comment by langyoung** [comment]
Sorry ,it was mistake before, Astherus should be list "Derivatives",We already support LST for perp trading

**Comment by realdealshaman** [comment]
updated to "Derivatives"
