### ISSUE TITLE
Balancer and Uniswap Defillama Ids Borked

### ISSUE THREAD

**Issue by SebMelendez01** [DefiLlama/DefiLlama-Adapters#10932]
Hello 😃 I wanted to flag the following issue. Some of the endpoints return different values for the defillamaId. 
The [protocols endpoint](https://api.llama.fi/protocols) (`/protocols`) returns the following ids for the protocols:
1. `balancer-v2`: `2611`
2. `uniswap-v1`: `2196`
3. `uniswap-v2`: `2197`
4. `uniswap-v3`: `2198`

The [Fees](https://api.llama.fi/summary/fees/uniswap-v3?dataType=dailyFees) (`/summary/fees/{slug}?dataType=dailyFees`) and [Revenue](https://api.llama.fi/summary/fees/uniswap-v3?dataType=dailyRevenue) (`/summary/fees/{slug}?dataType=dailyRevenue`) Endpoints return the following ids:
1. `balancer-v2`: `116`
2. `uniswap-v1`: `1`
3. `uniswap-v2`: `1`
4. `uniswap-v3`: `1`

**Comment by realdealshaman** [comment]
Hey, @SebMelendez01 , thanks for raising this issue, it is something we've been looking into, this issue got fixed on our v2 of fees api, so will be fixed soon once we switch to it
