### ISSUE TITLE
No price for Kernel USD (kUSD)

### ISSUE THREAD

**Issue by matstyler** [DefiLlama/DefiLlama-Adapters#11201]
I can see Kernel platform has been added: https://github.com/DefiLlama/DefiLlama-Adapters/blob/f549596a8390dbd92a5a5a5b7d23d6e1ffb484d7/projects/kernel/index.js

Even so I am not able to fetch the `kUSD` price. At the same time prices for `krETH` and `ksETH` are available.

Price API:
```
https://coins.llama.fi/prices/current/ethereum:0x0bb9ab78aaf7179b7515e6753d89822b91e670c4
```

**Comment by realdealshaman** [comment]
hey, this has now been fixed
