### ISSUE TITLE
Update Umoja Description

### ISSUE THREAD

**Issue by DarkRoku12** [DefiLlama/DefiLlama-Adapters#11280]
Our CEO, Robby Greenfield, would like to have our 'description' updated in [Umoja](https://defillama.com/protocol/umoja-protocol#information).

Short Description (to be shown on DefiLlama):
> Umoja is DeFi’s structured product and trade execution layer, offering seamless access to low-risk, high-yield crypto assets through ‘smartcoins.’ These innovative, crypto-collateralized digital assets are designed to protect principal while generating sustainable yields, making wealth creation effortless and accessible to everyone.

Merged PR [here](https://github.com/DefiLlama/DefiLlama-Adapters/pull/11075).

**Comment by realdealshaman** [comment]
updated! Thanks
