### ISSUE TITLE
Wrong website link for Palmy Finance

### ISSUE THREAD

**Issue by hide-yoshi** [DefiLlama/DefiLlama-Adapters#11393]
The website link on the Palmy Finance page appears to be incorrect.

Page: https://defillama.com/protocol/palmy-finance#information
The correct link is https://app.palmy.finance/, but actually it incorrectly links to https://yaka.finance/swap?inputCurrency=SEI&outputCurrency=0xB75D0B03c06A926e488e2659DF1A It is linked to 861F860bD3d1.

<img width="691" alt="image" src="https://github.com/user-attachments/assets/97fee262-cc23-499f-ac91-af860a9383e2">

**Comment by Define101** [comment]
https://github.com/DefiLlama/defillama-server/pull/7854
Should be good within 2 hours
