### ISSUE TITLE
Incorrect tvl data of mimo project on iotex chain

### ISSUE THREAD

**Issue by zongzheng123** [DefiLlama/DefiLlama-Adapters#11410]
Hello team, I am the memeber of iotex, i found the tvl data of mimo project on our chain from Aug22 looks like incorrect, can anyone help to take a look?https://defillama.com/protocol/mimo#information
![image](https://github.com/user-attachments/assets/88f15f1d-dd22-4eb0-b9dd-eaea41b6174c)
There's a cliff descent here that's weird

**Comment by realdealshaman** [comment]
hey, this has now been fixed
