### ISSUE TITLE
Missing osGNO-GNO Pool

### ISSUE THREAD

**Issue by olaviko** [DefiLlama/DefiLlama-Adapters#11428]
Hello,

I noticed that when filtering pools by the token GNO, the osGNO-GNO liquidity pool on Balancer is not appearing. Could you please add the osGNO-GNO pool to the list?

Filter applied: https://defillama.com/yields?token=GNO
osGNO-GNO pool: https://balancer.fi/pools/gnosis/v2/0x3220c83e953186f2b9ddfc0b5dd69483354edca20000000000000000000000b0

Thank you!

**Comment by realdealshaman** [comment]
Hey @olaviko thanks for raising this issue, this has been forwarded to our yield dashboard dev. If you still do not see the pool, please reach out on our discord. Thanks

Join the community: [http://discord.defillama.com](https://t.co/6eLY0pOKJX)
