### ISSUE TITLE
Add Charge DeFi on BSC

### ISSUE THREAD

**Issue by oscarsiauw** [DefiLlama/DefiLlama-Adapters#1145]
https://www.chargedefi.fi/

Contracts:
Static: 0x7dEb9906BD1d77B410a56E5C23c36340Bd60C983
Charge: 0x1C6bc8e962427dEb4106aE06A7fA2d715687395c
Pulse: 0xbceBAeAF1160Edc84D81A8f2D075858eE3960e9E

**Comment by 0xngmi** [comment]
pls explain which methods to call to get tvl

**Comment by 0xngmi** [comment]
PR has been created, closing this issue
