### ISSUE TITLE
Incorrect historical TVL data (Aqua-network)

### ISSUE THREAD

**Issue by dry-cake** [DefiLlama/DefiLlama-Adapters#11476]
Hi there. seems like Aquarius Stellar historical tvl is wrong.
From the last code update, data is correct, but all history is a little bit wrong.

I dont know exactly how your adapters fills or stores data, but can you pls rerun historical TVL and volume data collector?

On the screen u can see 712K$ historical TVL, but maximum from our API is ~672K$ at this moment

Volume data is also seems a little more than in our API.
https://amm-api.aqua.network/api/external/v1/statistics/totals/?size=all (For usd should be divided by 1e7)
<img width="862" alt="image" src="https://github.com/user-attachments/assets/4d072597-5635-4c0d-939b-341a4e8b46f7">

Thx in advance

**Comment by realdealshaman** [comment]
Hey, thanks for pointing this out. I've refilled historical data starting from the 29th aug, the changes will show in about 2 hours
