### ISSUE TITLE
Anchor version update

### ISSUE THREAD

**Issue by dmitrykarpushkin** [DefiLlama/DefiLlama-Adapters#11519]
Hello, I'm from Banx.gg

is it possible to install 0.30.1 version of @coral-xyz/anchor? At the moment I can't update the adapter because IDL can't be parsed

**Comment by realdealshaman** [comment]
I'll tag @g1nt0ki here, who can best help us with this

**Comment by g1nt0ki** [comment]
hi @dmitrykarpushkin do you if it has any breaking changes? sorry for the late reply

**Comment by dmitrykarpushkin** [comment]
@g1nt0ki
yes, it has. We needed it to integrate the Core NFT into the protocol. And in any case, sooner or later all protocols will switch to a new version of anchor

**Comment by g1nt0ki** [comment]
again, sorry for the delay, it is done now
