### ISSUE TITLE
Update Information of Biconomy-cex

### ISSUE THREAD

**Issue by flying-go** [DefiLlama/DefiLlama-Adapters#11560]
Could you please update our logo as https://ibb.co/N9YK1Wm and update our name from 'Biconomy Cex' to 'Biconomy.com' and add the following to the 'Exchange Information':
"[Biconomy.com](http://biconomy.com/) is a centralized cryptocurrency exchange, established in 2019 and registered in the British Virgin Islands."?

**Comment by realdealshaman** [comment]
Hey, thanks for the info, I've made the requested changes and it will show in the next couple of hours
