### ISSUE TITLE
I'd like to add GOPAX exchange on DefiLlama.

### ISSUE THREAD

**Issue by LilyGOPAX** [DefiLlama/DefiLlama-Adapters#11677]
Can I add GOPAXexchange on DefiLlama? It's based on South Korea.
URL: https://www.gopax.co.kr/ 
Twitter: https://x.com/gopax_kr

If you need any further information, please tell me so that I can provide detailed information.

**Comment by realdealshaman** [comment]
Hey @LilyGOPAX what is GOPAX? Is it a CEX or a DEX?

**Comment by realdealshaman** [comment]
closing this for now, due to inactivity. Please open a new issue with more info once ready. Thanks
