### ISSUE TITLE
OracleFreeDollar wrong TVL

### ISSUE THREAD

**Issue by NightHarbor** [DefiLlama/DefiLlama-Adapters#11800]
Hi, I've noticed that OracleFreeDollar protocol has caching problems for TVL value. 
I've noticed that the value has not been updated with the actual code, and setting `skipCache:true` inside `getLogs2()` returns the correct TVL value.

The actual code reads the old value:

![Screenshot 2024-10-01 alle 19 27 36](https://github.com/user-attachments/assets/bb8f79dd-3e24-4ada-96af-ad14f8b5a989)

With `skipCache:true`:

![Screenshot 2024-10-01 alle 19 28 55](https://github.com/user-attachments/assets/cfdaf630-bf1a-4aa9-adfa-0178ea8f5cb0)

Is there something we can do to fix this?
I see that disabling the cache makes the read very slow and not so efficient.

Thank you 😄

**Comment by g1nt0ki** [comment]
hi, unsure what happened, cleared log cache and getting correct values now, sorry about this, we will fix the chart

**Comment by g1nt0ki** [comment]
also, sorry for the late reply
