### ISSUE TITLE
TVL data on DefiLlama dashboard isn't getting updated for Filament Finanace

### ISSUE THREAD

**Issue by rajeebkm** [DefiLlama/DefiLlama-Adapters#12024]
Hi Team,

TVL isn't getting updated on DefiLlama dashboard. It should be updated. It is showing ~$105K. Please have a look into it.

https://github.com/DefiLlama/DefiLlama-Adapters/pull/11735#issuecomment-2434472637

Thanks

**Comment by 0xngmi** [comment]
`node test.js projects/filament/index.js` returns the same as displayed on defillama.com
