### ISSUE TITLE
DarkMatter TVL is wor

### ISSUE THREAD

**Issue by darkmatterdefi** [DefiLlama/DefiLlama-Adapters#1246]
![image](https://user-images.githubusercontent.com/87251771/147841720-9e5fb2ef-7629-46c1-8b19-9eea3dff2178.png)
![image](https://user-images.githubusercontent.com/87251771/147841729-1a2a38af-1bf4-45fb-a64a-d747c54f407f.png)
the tvl of darkmatter in fantom reflects value 0 please review.

**Comment by darkmatterdefi** [comment]
@0xngmi you can take a look, please

**Comment by 0xngmi** [comment]
what value should it be?

**Comment by darkmatterdefi** [comment]
now it is correct, but it was at 0 for several minutes.
