### ISSUE TITLE
TVL has suddenly dropped down. 

### ISSUE THREAD

**Issue by zolotokrylin** [DefiLlama/DefiLlama-Adapters#12518]
Hey guys,
Vadim from Clearpool (https://defillama.com/protocol/clearpool#information) here.

There is an issue with a sudden TVL drop (27th of Nov): https://defillama.com/protocol/clearpool-tpool#information

We didn't introduce any chances in adapter (https://github.com/DefiLlama/DefiLlama-Adapters/tree/c03f138f17bf858365c04ae4252d6144205a282e/projects/clearpool) nor smart-contracts.

Why TVL is down? 

Thank you in advance for your support!

**Comment by 0xngmi** [comment]
The issue is likely that pricing for USDX failed

**Comment by realdealshaman** [comment]
Hey @zolotokrylin I see that the chart is now back to normal and I have updated those dates to remove the drops in TVL

**Comment by realdealshaman** [comment]
closing this issue for now.

**Comment by zolotokrylin** [comment]
Thank you very much @realdealshaman 🧡
