### ISSUE TITLE
Update new logo for edgeX

### ISSUE THREAD

**Issue by sean35809** [DefiLlama/DefiLlama-Adapters#12567]
Please kindly update the new logo for edgeX, thank you.

DefiLlama listing: https://defillama.com/protocol/edgex

New logo: 
![img_v3_02h9_dea8f1ee-c91d-4ae3-a08f-d71aa01125hu](https://github.com/user-attachments/assets/1f8e2a58-c713-4f14-baa0-124cc7a9b975)

**Comment by realdealshaman** [comment]
Hey @sean35809 this is now updated, it will be live in about one hour. Please remember to delete your local cache to see it
