### ISSUE TITLE
Request pluto-so mark as audited

### ISSUE THREAD

**Issue by verzth** [DefiLlama/DefiLlama-Adapters#12716]
List of Audit Link:
https://docs.pluto.so/security/audit
- QuilAudits: https://676418262-files.gitbook.io/~/files/v0/b/gitbook-x-prod.appspot.com/o/spaces%2Fu4dm7dRSq1KjHR83LZ5d%2Fuploads%2FrQ9JRNspDf1bm6MDc2j7%2FPluto%20Smart%20Contracts%20Audit%20Report%20-%20QuillAudits.pdf?alt=media&token=3ceb0a72-f0e0-4a85-861a-874af02a5b0a

**Comment by realdealshaman** [comment]
Hey @verzth , thanks for providing the links. I've added them to the listing and they will show on our UI in about one hour
