### ISSUE TITLE
Hyperliquid perp's TVL counted with USDT but actually its USDC

### ISSUE THREAD

**Issue by yoshiso** [DefiLlama/DefiLlama-Adapters#12711]
As written in title, it seems like hyperliquid's TVL is written with USDT balance, but actually its USDC.

https://github.com/DefiLlama/DefiLlama-Adapters/blob/10a31fd9e595cc060880f4862ae35cd6c35f3057/projects/hyperliquid-perp/index.js#L6

**Comment by realdealshaman** [comment]
Hey @yoshiso thanks for the ping on this, Our adapter for the perps product is still a wip. I have however updated the calculation in the current adapter, in it's current state, to use usdc instead of usdt
