### ISSUE TITLE
Add lisUSD staking into optional TVL

### ISSUE THREAD

**Issue by tyler-tsai** [DefiLlama/DefiLlama-Adapters#12763]
Can we count this service into optional TVL?

https://lista.org/earn/deposit/USDT

**Comment by tyler-tsai** [comment]
hi @g1nt0ki , could you please help with this?

**Comment by g1nt0ki** [comment]
not sure how I can help, it is not very clear how that staking works works and you have not shared any smart contract address :(

**Comment by tyler-tsai** [comment]
Our DeFi protocol offers a seamless staking mechanism:

Users deposit USDT into our protocol
The protocol automatically converts USDT to lisUSD
The converted lisUSD is automatically staked
Users earn staking rewards from their lisUSD position

You can see locked lisUSD here.
Smart Contract: 0x37DB1AE9B24055D1F9fE973Aea40B7EB2995D0Bf

**Comment by tyler-tsai** [comment]
There is another question, we have two protocols, LSR and CDP.
We calculate TVL across our two protocols (LSR and CDP) with an 'Adjusted TVL' metric to account for asset overlap:
Example flow:

1. User deposits BNB → gets slisbnb (LSR TVL)
2. User stakes slisbnb in CDP (CDP TVL)
3. These slisbnb are counted once in Adjusted TVL

Adjusted TVL = Total TVL - Overlapped Assets

Can we put the overlap part into optional TVL, because they are two different protocols.

**Comment by g1nt0ki** [comment]
> There is another question, we have two protocols, LSR and CDP. We calculate TVL across our two protocols (LSR and CDP) with an 'Adjusted TVL' metric to account for asset overlap: Example flow:
> 
>     1. User deposits BNB → gets slisbnb (LSR TVL)
> 
>     2. User stakes slisbnb in CDP (CDP TVL)
> 
>     3. These slisbnb are counted once in Adjusted TVL
> 
> 
> Adjusted TVL = Total TVL - Overlapped Assets
> 
> Can we put the overlap part into optional TVL, because they are two different protocols.

this is already being discussed in the tg group?

**Comment by g1nt0ki** [comment]
> Our DeFi protocol offers a seamless staking mechanism:
> 
> Users deposit USDT into our protocol The protocol automatically converts USDT to lisUSD The converted lisUSD is automatically staked Users earn staking rewards from their lisUSD position
> 
> You can see locked lisUSD here. Smart Contract: 0x37DB1AE9B24055D1F9fE973Aea40B7EB2995D0Bf

if the pool doesnt hold tether but converts to to lisUSD whose backing we already count towards tvl, wouldnt counting this lead to doublecounbting?

**Comment by tyler-tsai** [comment]
We never count this part as TVL before, I figure that it won’t cause double
counting

**Comment by g1nt0ki** [comment]
we are not counting backing of lisuSD as tvl?

**Comment by tyler-tsai** [comment]
In LISTA DAO, we currently count liquid staking and collateral deposit as TVL.
The address I provided differs from these two, so it won't be double-counted.

**Comment by tyler-tsai** [comment]
collateral deposit
https://defillama.com/protocol/lisusd#information

liquid staking
https://defillama.com/protocol/slisbnb#information

**Comment by g1nt0ki** [comment]
no, the address you shared has lisUSD, but we are tracking the backing of lisUSD under lisUSD listing right?

**Comment by tyler-tsai** [comment]
Oh, you mean We can't track lisUSD on protocol backing lisUSD?

**Comment by tyler-tsai** [comment]
> > There is another question, we have two protocols, LSR and CDP. We calculate TVL across our two protocols (LSR and CDP) with an 'Adjusted TVL' metric to account for asset overlap: Example flow:
> > ```
> > 1. User deposits BNB → gets slisbnb (LSR TVL)
> > 
> > 2. User stakes slisbnb in CDP (CDP TVL)
> > 
> > 3. These slisbnb are counted once in Adjusted TVL
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Adjusted TVL = Total TVL - Overlapped Assets
> > Can we put the overlap part into optional TVL, because they are two different protocols.
> 
> this is already being discussed in the tg group?

Are you Bentura in the tg group? cause I didn't get a response there.

**Comment by g1nt0ki** [comment]
> Oh, you mean We can't track lisUSD on protocol backing lisUSD?

yes, exactly.

**Comment by tyler-tsai** [comment]
Thanks for your patience!
