### ISSUE TITLE
SmartDEX on SBCH was wrongly added

### ISSUE THREAD

**Issue by smartdogebch** [DefiLlama/DefiLlama-Adapters#1392]
Hi,

I have made a pull request and SmartDEX was added to the DefiLama but there seems to be an issue.
https://github.com/DefiLlama/DefiLlama-Adapters/pull/1381

When you go to the SmartBCH chain page there is SmartDEX (Dsmart) with a wrong logo than what I have put in the pull request. TVL and name are ok.
![image](https://user-images.githubusercontent.com/95665072/149601391-f440c919-279e-4f89-a5d8-30bb92d0400b.png)

Next when I click on the `SmartDEX (Dsmart)` from the list I am taken to the following link https://defillama.com/protocol/smartdex which is not SmartDEX on the SBCH network but another one under the same name on Polygon network.

Could you please take a look at it and possibly fix the issue?

Thanks in advance!

**Comment by 0xngmi** [comment]
Looking into it it seems like this has already been fixed, could you confirm it?

**Comment by smartdogebch** [comment]
You are correct it was fixed, checked it now it was fixed in the meantime.
