### ISSUE TITLE
update ioTube token symbol

### ISSUE THREAD

**Issue by uu-z** [DefiLlama/DefiLlama-Adapters#1416]
hi, we want update the token symbol from $CIOTX -> $IOTX
![image](https://user-images.githubusercontent.com/12439992/149866461-27bc0055-6c21-436e-be62-b46a9adcb48a.png)

also please update the coingecko and coinmarketcap id, thanks.
https://www.coingecko.com/en/coins/iotex
https://coinmarketcap.com/currencies/iotex

**Comment by waynebruce0x** [comment]
Isn't IOTX the chain gas token though?

**Comment by guo** [comment]
ioTube does not have its governance token yet. CIOTX is one assets on the bridge. Maybe we can simply remove $CIOTX from the title.

**Comment by 0xngmi** [comment]
Token has been removed

**Comment by guo** [comment]
Thanks!
