### ISSUE TITLE
Cyclone TVL display issue

### ISSUE THREAD

**Issue by bf945** [DefiLlama/DefiLlama-Adapters#1506]
There seems to be a mismatch between the page data and the script output. Please help check it out, thanks.
https://defillama.com/protocol/cyclone

![image](https://user-images.githubusercontent.com/73311932/151655065-ad1950c6-39d9-4633-900c-1aa1eaa8d3db.png)
![image](https://user-images.githubusercontent.com/73311932/151655125-e803427e-1d1e-4500-bf02-a039ce53621f.png)

**Comment by waynebruce0x** [comment]
I think it's because we're having trouble getting block heights from our iotex RPC. We'll try and fix it

**Comment by waynebruce0x** [comment]
I'm getting this
<img width="233" alt="Screenshot 2022-01-31 at 15 58 26" src="https://user-images.githubusercontent.com/24625596/151827839-e5898d75-5f3a-473e-864e-97789cb5b980.png">

**Comment by bf945** [comment]
@waynebruce0x It seems that the data is still not correct. Is there any progress?
