### ISSUE TITLE
Update Aquarius information

### ISSUE THREAD

**Issue by AquariusFi** [DefiLlama/DefiLlama-Adapters#171]
##### Token address and ticker if any: 
 - AQU: https://ftmscan.com/token/0x0f7ADb77B6334B9B5A3c4f78aAa073eA1D915bF6
 - aUSD: https://ftmscan.com/token/0x41e3dF7f716aB5AF28c1497B354D79342923196a

##### [Optional] ETH addresss (to receive a LlamaPunk): 0xA4e9ee03e8BFa3EB195A90B9cd4b9BE8E9D8fEB7

**Comment by 0xngmi** [comment]
Could you apply the changes directly to https://github.com/DefiLlama/defillama-server/blob/master/src/protocols/data.ts#L4123? This will make it easier to see what should be changed

**Comment by AquariusFi** [comment]
> Could you apply the changes directly to https://github.com/DefiLlama/defillama-server/blob/master/src/protocols/data.ts#L4123? This will make it easier to see what should be changed

Okay, I'll do that. Thank you very much.

**Comment by 0xngmi** [comment]
Solved in https://github.com/DefiLlama/defillama-server/pull/10
