### ISSUE TITLE
Suggestion to add WAX chain

### ISSUE THREAD

**Issue by DenisCarriere** [DefiLlama/DefiLlama-Adapters#1729]
## website
http://wax.io/

## block explorer
https://wax.bloks.io/

## description
WAX is a purpose-built NFT blockchain

## Logo

https://user-images.githubusercontent.com/550895/155409180-de17b5c6-7660-4d3f-8f5c-d1d6b8e5e7eb.png
![image](https://user-images.githubusercontent.com/550895/155409180-de17b5c6-7660-4d3f-8f5c-d1d6b8e5e7eb.png)

## CoinGecko token details

- symbol: WAX
- https://www.coingecko.com/en/coins/wax

## Adapters
- Defibox WAX adapter: https://github.com/DefiLlama/DefiLlama-Adapters/pull/1725

**Comment by DenisCarriere** [comment]
❗ wrong symbol for chain `WAKP`

<img width="226" alt="image" src="https://user-images.githubusercontent.com/550895/155733483-6f108d58-9ffe-4ac6-a4f3-7f5b762c27f5.png">

Could simply be `WAX`

**Comment by realdealshaman** [comment]
Hey sorry about that and thanks for pointing it out, I just updated it to keep it consistent across other sites, logo will appear shortly as well and we will tweet out the new chain listing 🥳

**Comment by 0xngmi** [comment]
Looks like this has been solved

**Comment by DenisCarriere** [comment]
@0xngmi Yes, solved, thanks for the support 🙏
