### ISSUE TITLE
why elysia tvl is $0?

### ISSUE THREAD

**Issue by copyNdpaste** [DefiLlama/DefiLlama-Adapters#1744]
Hello, my PR merged and I checked site below. Contrary to what I expected, tvl is $0. So I tried to run my code on local and logs were fine.

What is the problem? Could u resolve it plz?

https://defillama.com/protocol/elysia

![image](https://user-images.githubusercontent.com/18900976/155640480-f1010a9c-f847-480c-b2c4-611f540be073.png)

And need to be modified as below too.
title : Elysia -> ELYFI
Token Information : Elysia -> ELYFI
LOGO : ![image](https://user-images.githubusercontent.com/18900976/155669560-5e4b9b40-81ec-4f0c-bb65-a32c9ddb6f45.png)
Thank you.

**Comment by copyNdpaste** [comment]
@waynebruce0x @realdealshaman @0xngmi Hello check this out plz!

**Comment by waynebruce0x** [comment]
Sure, will look into this

**Comment by waynebruce0x** [comment]
its because the exports were in the wrong format, in future use 'node test.js <path to adapter>' to see what the results will be. Should be fixed in an hour
