### ISSUE TITLE
DarkMatter issue tvl 

### ISSUE THREAD

**Issue by darkmatterdefi** [DefiLlama/DefiLlama-Adapters#1801]
hey, our tvl has problems, it throws 0 every so often, you guys could review it.

 
![image](https://user-images.githubusercontent.com/87251771/156439323-072ce0de-4567-42aa-ac68-6539a0dc3f80.png)
![image](https://user-images.githubusercontent.com/87251771/156439380-26755397-8df4-446c-a29c-7f154f0d21cd.png)

**Comment by darkmatterdefi** [comment]
@0xngmi might check.

**Comment by waynebruce0x** [comment]
thanks for flagging, will look into this

**Comment by waynebruce0x** [comment]
There doesnt seem to be anything wrong with the adapter, so I suspect its an RPC issue (common on fantom). I'll see if there's something we can do to smooth the data coming from the API
