### ISSUE TITLE
API key committed to repo

### ISSUE THREAD

**Issue by codefly** [DefiLlama/DefiLlama-Adapters#1841]
you have committed your Blockfrost API key to a public repository, see here: 
https://github.com/DefiLlama/DefiLlama-Adapters/blob/main/projects/minswap/index.js

I would recommend removing that and adding it via an environment variable wherever you have deployed this code. Additionally you should probably rotate that key!

**Comment by 0xngmi** [comment]
yeah, aware, tbh its just a free account and nobody has stolen it so planning to keep it that way

**Comment by 122wr** [comment]
(1)
