### ISSUE TITLE
Add Tethys Market and merge its TVL with Tethys DEX TVL

### ISSUE THREAD

**Issue by meyers4549** [DefiLlama/DefiLlama-Adapters#1982]
Hello!

We already have a Uniswap V2 DEX adapter live and well working for our exchange:

https://defillama.com/protocol/tethys-finance
https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/projects/tethys

We launched a new lending protocol inside DEX (same thing as TraderJoe did), as a base protocol we chose Tarot, which also has live adapter:

https://defillama.com/protocol/tarot
https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/projects/tarot

We ask for help in getting our lending protocol tracked as well and TVL merged with our DEX TVL. The contracts of our lending implementation can be found here:

https://docs.tethys.finance/info/contracts#lending-contracts

Thanks in advance ❤️

**Comment by waynebruce0x** [comment]
Do you use the same event type and architecture as tarot? A straight port of their code doesnt seem to work

**Comment by meyers4549** [comment]
Hello, @waynebruce0x! Thanks for taking time helping us on this issue.

It should be the same in general, however we are on Metis network instead of Fantom, maybe thats the case.

Also more details on our factory deployment:

Address - 0x15294FF72D7a3D21E52111a3D428d1964f93c63B
Starting block - 847330

**Comment by 0xngmi** [comment]
something to be careful here is to avoid double-counting between LPs in dex and leveraged LPs in market, i think the only thing we should add are the single token pools

**Comment by waynebruce0x** [comment]
Can you verify the factory contract at 0x15294FF72D7a3D21E52111a3D428d1964f93c63B?
