### ISSUE TITLE
Change elyfi logo and audit link and protocol name please

### ISSUE THREAD

**Issue by copyNdpaste** [DefiLlama/DefiLlama-Adapters#2062]
changed audit link : 
https://www.certik.com/projects/elyfi

protocol(project) name :
Elysia -> ELYFI (uppercase)

logo : 
![image](https://user-images.githubusercontent.com/18900976/160329340-a42f7066-097a-4008-900b-3dc9021f965f.png)

**Comment by waynebruce0x** [comment]
will do this asap
