### ISSUE TITLE
[StakeDAO] Discrepancy in harmony TVL displayed on UI

### ISSUE THREAD

**Issue by PumpkingWok** [DefiLlama/DefiLlama-Adapters#2141]
It seems that there is a discrepancy in the harmony TVL calculation, between the one displayed on the UI and the one fetched by the resolver.

<img width="472" alt="Screen Shot 2022-04-02 at 11 48 38 AM" src="https://user-images.githubusercontent.com/2848253/161377666-ecff2363-c773-471a-9626-b8cf829ea5aa.png">

The UI displays $46.59m for the harmony network, but instead the resolver can retrieve the correct TVL value, $74m. It seems that the USDC total value in $ is missing via the UI.

<img width="405" alt="Screen Shot 2022-04-02 at 11 50 15 AM" src="https://user-images.githubusercontent.com/2848253/161377722-553eb9d2-0b6b-433c-aec8-98b17bb22a20.png">

Thanks a lot in advance.

**Comment by waynebruce0x** [comment]
The UI data is about 10 days old because the resolver runs into an error: 
Error: missing revert data in call exception [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (code=CALL_EXCEPTION, version=providers/5.6.2)
we're looking into fixing it

**Comment by PumpkingWok** [comment]
Thanks a lot for the reply. If the issue is at stakeDAO resolver side, i can look in it without problems.
Thanks in advance.

**Comment by PumpkingWok** [comment]
Hi @waynebruce0x , any news about this issue. thanks a lot in advance.

**Comment by PumpkingWok** [comment]
HI @waynebruce0x , any news about that. I have just checked and it seems that the TVL issue is not related only for the harmony network.

<img width="379" alt="Screen Shot 2022-05-04 at 11 43 22 AM" src="https://user-images.githubusercontent.com/2848253/166658559-94d6f977-6f0b-4538-a9ce-f4ffc5046453.png">

The TVL reports around the same $ value since this date. There are other external services that notify to us these infos using your API endpoint, so it should be pretty urgent to fix.
Thanks a lot in advance.

**Comment by PumpkingWok** [comment]
Hi @waynebruce0x , thanks a lot, really.
I have just checked and the TVL displayed is correct. I'm going to create a PR during the day for including the last vaults deployed by StakeDAO. thanks.
