### ISSUE TITLE
pegasus TVL  not correct

### ISSUE THREAD

**Issue by PegasusDollar** [DefiLlama/DefiLlama-Adapters#2168]
why total value lock is 0$
we have genesis pool 
![image](https://user-images.githubusercontent.com/101194125/161814161-db332d67-fec1-44dc-8262-d624d8cd6d54.png)
And my code was replace by this  code.
![image](https://user-images.githubusercontent.com/101194125/161814288-63b346fd-f576-43eb-9e4b-b72662498593.png)
it's not match.

**Comment by PegasusDollar** [comment]
how can i fix it

**Comment by waynebruce0x** [comment]
Can you send us the contract addresses? Is there a factory for these pools?

**Comment by PegasusDollar** [comment]
this is pegasus contracts:
Boardroom(stake): 0x7614A4CEB3ACdfCd4841D7bD76c30e7a401E83cd
Genesis pool (earn PES): 0x64bfcbe4480b53e8234ca258a96720f29fe6a6fb
Earn SPES Pool: 0xdd403db142a320261858840103b907c2486240c6
Thank you!

**Comment by PegasusDollar** [comment]
Seem like u missing genesis pool earn PES when u change my code.
And why tvl not show. Only show staking and pool2.
What do we need to show tvl?

**Comment by waynebruce0x** [comment]
https://github.com/DefiLlama/DefiLlama-Adapters/pull/2252
