### ISSUE TITLE
EverRise contract address

### ISSUE THREAD

**Issue by beneverrise** [DefiLlama/DefiLlama-Adapters#2329]
Old contract address (`0x0cD022ddE27169b20895e0e2B2B8A33B25e63579`) is used for display and links
New contract address is `0xC17c30e98541188614dF99239cABD40280810cA3`

![image](https://user-images.githubusercontent.com/87881922/164042983-688a875b-a3ec-47fa-9411-2878e164b5be.png)

https://etherscan.io/token/0xC17c30e98541188614dF99239cABD40280810cA3

Also is second Audit by Chainsulting for new contract https://github.com/chainsulting/Smart-Contract-Security-Audits/tree/master/EverRise

![image](https://user-images.githubusercontent.com/87881922/164043923-45c619df-2ff6-4c88-abd3-aac263a7574e.png)

Not sure how to update? Thank you

**Comment by realdealshaman** [comment]
added the new contract address and new audit link. Thanks

**Comment by beneverrise** [comment]
Perfect thank you 💜
