### ISSUE TITLE
Incorrect Data for Thales

### ISSUE THREAD

**Issue by LeifuChen** [DefiLlama/DefiLlama-Adapters#2525]
The discrepancies could be observed from the website and the local test.
From the [website](https://defillama.com/protocol/thales), staking is 0.
![image](https://user-images.githubusercontent.com/4819006/166687984-5f138e82-442e-491b-ad32-56fe82766792.png)

However, when I run the code locally (`node test.js projects/thales/index.js`).
It's clear that the staking number is $3.05M.
![image](https://user-images.githubusercontent.com/4819006/166688105-951e3e3c-3173-4038-bd18-00383048e19f.png)

Thanks for checking this issue.

**Comment by ThomasDev62** [comment]
Have you able resolved your issues?

**Comment by LeifuChen** [comment]
The issue has been fixed.
![image](https://user-images.githubusercontent.com/4819006/168802613-03ad5df4-994d-4377-a490-06ff8959f2b5.png)
