### ISSUE TITLE
The adapter at projects/plenty exports TVL:

### ISSUE THREAD

**Issue by Mustafakc** [DefiLlama/DefiLlama-Adapters#2821]
The adapter at projects/plenty exports TVL: 
        
 
 
    tezos-staking             190.59 k
    tezos                     1.50 M
    staking                   190.59 k
    
    total                    1.50 M

_Originally posted by @llamatester in https://github.com/DefiLlama/DefiLlama-Adapters/issues/2817#issuecomment-1140943240_

**Comment by Mustafakc** [comment]
Sorun şu aylardır ağda olduğu söylenen ve benimde gördüğüm birtakım Token ve ntf leri kullanmak istiyorum yapamıyorum yardım kimden isteyeceğim bilmiyorum ne yapmam gerektiğini bilmiyorum bir takım yönergelerle yapmaya çalıştım olmadı bir kişi bana yardımcı olursa gerçekten çok büyük bir iyilik yapmış olur buraya bunu yazmak doğrumu onuda bilmiyorum yanlış bir hata yaptıysam özür dilerim doğru yaptıysam yardım etmek isteyen bir arkadaş olursa çok sevinirim belki fazla olucak ama bugün bitmaden yardımcı olursa tahmin edemiyecegi bir iyilik yapmış olur çok teşekkür ederim yanlış birşey yazdıysam bu acemi olduğumdan kaynaklıdır af edersiniz mustafakoc.arsali@gmail.com

**Comment by g1nt0ki** [comment]
> Sorun şu aylardır ağda olduğu söylenen ve benimde gördüğüm birtakım Token ve ntf leri kullanmak istiyorum yapamıyorum yardım kimden isteyeceğim bilmiyorum ne yapmam gerektiğini bilmiyorum bir takım yönergelerle yapmaya çalıştım olmadı bir kişi bana yardımcı olursa gerçekten çok büyük bir iyilik yapmış olur buraya bunu yazmak doğrumu onuda bilmiyorum yanlış bir hata yaptıysam özür dilerim doğru yaptıysam yardım etmek isteyen bir arkadaş olursa çok sevinirim belki fazla olucak ama bugün bitmaden yardımcı olursa tahmin edemiyecegi bir iyilik yapmış olur çok teşekkür ederim yanlış birşey yazdıysam bu acemi olduğumdan kaynaklıdır af edersiniz [mustafakoc.arsali@gmail.com](mailto:mustafakoc.arsali@gmail.com)

I am hoping deepl translated this correctly:

    The problem is that I want to use a number of tokens and ntfs that are said to be on the network for months and that I have seen for months, I can't do it, I don't know who to ask for help, I don't know what to do, I don't know if it is right to write this here, I apologize if I made a mistake, if I did it right, I would be very happy if there is a friend who wants to help, maybe it will be too much, but if it helps me today, it will do a favor that it cannot guess, thank you very much, if I wrote something wrong, it is because I am a beginner. 

Sorry, but this is not the right forum, closing this issue
