### ISSUE TITLE
Modify short description for ApolloX token

### ISSUE THREAD

**Issue by AQVYmeCkJsFTFWpMAHmA** [DefiLlama/DefiLlama-Adapters#2937]
Hello,

https://github.com/DefiLlama/DefiLlama-Adapters/pull/2710

We would like to change the short description for ApolloX token showed on defilama:

https://defillama.com/protocol/apollox

<img width="698" alt="image" src="https://user-images.githubusercontent.com/105714995/173040591-c17d9eb5-8d21-420f-af44-26d3c076fcbf.png">

Change to below description
`ApolloX Finance is a decentralized crypto trading exchange. Unlike the common Automated Market Makers model (AMM) which is adopted by other decentralized exchanges, ApolloX Finance adopts the order book model, which supports both spot and futures trading. By using off-chain order books and on-chain settlement, its protocol aims to create an efficient, fair and trustless financial market that is not controlled by any centralized organization.`

**Comment by g1nt0ki** [comment]
https://github.com/DefiLlama/defillama-server/commit/a48966bd9967e9ccd8936300b010897db530a6cc
