### ISSUE TITLE
Follow up on recently merged Nirvana TVL / staking

### ISSUE THREAD

**Issue by nirvana-sid** [DefiLlama/DefiLlama-Adapters#3037]
@waynebruce0x hello! I'm a Nirvana team member. I think there's some confusion about the TVL methodology that led to an inaccurate result at https://defillama.com/protocol/nirvana . If I understand [your comment](https://github.com/DefiLlama/DefiLlama-Adapters/pull/2914#issuecomment-1149371941) correctly, defillama will put the value from Nirvana's own platform token, ANA, in this optional "staking" category. However the protocol also holds a reserve treasury of stablecoins that currently adds up to ~$12.8M:

* https://solscan.io/account/EwQa93fpN2a6smD7EBFjQEyDt3DP8EMLHLjgAWxG9Qhj
* https://solscan.io/account/GX1bJw7nLj7pot1Kfq8UDrzzZVK3HnuyjY5FycErgrzG
* https://solscan.io/account/6t7ViNDULtkgvmntHsmi1QV73Tez7ZcX6DJvARHkfUJZ

Could be the basis for the protocol's base TVL?

_Originally posted by @rinswend in https://github.com/DefiLlama/DefiLlama-Adapters/issues/2914#issuecomment-1158118932_

**Comment by g1nt0ki** [comment]
@nirvana-sid I have added USDC & USDT balance as they can be considered protocol owned liquidity but not NIRV as it is protocol native token. https://github.com/DefiLlama/DefiLlama-Adapters/pull/3088/files
