### ISSUE TITLE
Algorand filter breaks front end to white screen.

### ISSUE THREAD

**Issue by Yieldlan** [DefiLlama/DefiLlama-Adapters#317]
https://defillama.com/chain/Algorand

**Comment by Yieldlan** [comment]
Seems to have resolved itself

**Comment by Yieldlan** [comment]
No, wait

It only breaks if you toggle on Staking TVL in settings, then go to the algorand page.

**Comment by 0xngmi** [comment]
Thanks for reporting, it should be fixed now

**Comment by 0xngmi** [comment]
Closing for now, let me know if anything else breaks :)
