### ISSUE TITLE
BlockNG TVL is highly inflated.

### ISSUE THREAD

**Issue by blacksheep1999** [DefiLlama/DefiLlama-Adapters#3199]
BlockNG is a DEX on smartBCH chain. Its TVL calculation is so different from other DEXes (MistSwap, TangoSwap, BenSwap, Verse, etc.) which results in a highly inflated number compared to other DEXes.

Let me share the detail with you.

The BlockNG TVL is calculted as the sum of these values.
![image](https://user-images.githubusercontent.com/108965435/178088531-c400fa13-1f29-4cf6-b834-24d621b9a132.png)
![image](https://user-images.githubusercontent.com/108965435/178088501-c4500a5f-7fdb-4ac4-b974-cf4883cf793a.png)

lawTVLs, bchTVLs, flexUSDTVLs get all liquidities from LPs no matter which DEX they are from or whether staked or not.
![image](https://user-images.githubusercontent.com/108965435/178088585-32dc02c1-8995-4825-bae1-dd7300dac309.png)
![image](https://user-images.githubusercontent.com/108965435/178088593-ca08411a-b9e9-4bf7-9715-a16da9aad5d8.png)

punksTVL uses a value represents its NFT series from and is fetched from a json file.
![image](https://user-images.githubusercontent.com/108965435/178088693-28235d0d-8ad8-437d-b817-90b3f0a2c3b4.png)

bentoTVLs are from its lending product, lawEtp is a token with almost no liquidity, and lawUSD has also very little liquidity and depegged from USD all the time.

All these combined resulted in a 5x - 10x inflation of its TVL.

My suggestions:
- Remove punkTVL because it is a self-calculated value of NFTs and they are not staked or locked anywhere
- Move bentoTVLs to lending.
- Remove lawTVLs, bchTVLs, flexUSDTVLs because these are not locked on BlockNG
- Use standard DEX liquidity plus the WBCH pool instead just like other DEXes

Source:
https://github.com/DefiLlama/DefiLlama-Adapters/blob/main/projects/blockng/index.js#L66

**Comment by g1nt0ki** [comment]
@blacksheep1999 thanks for raising this issue, I will work on refactoring their code to fix this
