### ISSUE TITLE
Tranchess TVL Graph Break on July 23rd

### ISSUE THREAD

**Issue by bill-clippy** [DefiLlama/DefiLlama-Adapters#320]
https://defillama.com/protocol/tranchess

There is an obvious drop in Tranchess's TVL graph in both dollar and BTCB units, which contradicts our telemetry.

Observe two data points sampled on July 23rd (the day we've the PR merged), versus one sample point for the rest of the dates. I suspect there is an overlapping of data points, and that the 39mio should come before 50mio, could you please help fixing the bug?

<img width="721" alt="july23-1" src="https://user-images.githubusercontent.com/80559444/126932171-9aa8bf3b-6b6c-41c8-b9df-4fbc904f8087.PNG">
<img width="728" alt="july23-2" src="https://user-images.githubusercontent.com/80559444/126932181-15998f63-97a0-40f6-bb87-7d83aac69616.PNG">

**Comment by 0xngmi** [comment]
Yeah it probably was a problem caused when refilling data. It should be fixed now

**Comment by bill-clippy** [comment]
Fix confirmed. Appreciate it!
