### ISSUE TITLE
APEX already has a token but is mentioned in the airdrops page

### ISSUE THREAD

**Issue by AyiSoli** [DefiLlama/DefiLlama-Adapters#3208]
Apex is mentioned in the airdrop page, added 6 days ago: https://defillama.com/airdrops

However it already has a token: https://docs.apex.exchange/apex-token/apex-token-introduction

https://www.coingecko.com/en/coins/apex-token

So it can be removed from the airdrops section.

**Comment by g1nt0ki** [comment]
thanks for raising this to our attention, we have  fixed it
