### ISSUE TITLE
Tranchess TVL Graph No New Data from July 25th to 26th

### ISSUE THREAD

**Issue by bill-clippy** [DefiLlama/DefiLlama-Adapters#323]
https://defillama.com/protocol/tranchess

For BTCB graph, the TVL on  26th is the same as 25th at 2605, which is not likely the case. I've verified that our SDK yields the correct result for the latest block, could you please help with the investigation?

In addition, it seems that the issue for BTCB graph still exists #320. I supposed the same fix for USD graph might apply here? Thanks for your time

**Comment by 0xngmi** [comment]
Yeah, I only applied the fix to the USD data, not the tokens. Good point

**Comment by bill-clippy** [comment]
Fix confirmed, thanks again!
