### ISSUE TITLE
Adapter still not seeming to be reflecting for some reason.

### ISSUE THREAD

**Issue by westonnelson** [DefiLlama/DefiLlama-Adapters#3231]
The adapter at projects/saddle exports TVL: 
        
 
 
    arbitrum                  2.82 M
    optimism                  2.57 k
    evmos                     162.37 k
    ethereum                  42.16 M
    fantom                    3.01 M
    
    total                    48.16 M

_Originally posted by @llamatester in https://github.com/DefiLlama/DefiLlama-Adapters/issues/3219#issuecomment-1181525523_

**Comment by westonnelson** [comment]
Thank you @g1nt0ki 

Is there any way/or a solve to show what the accurate TVL from DeFi Llama is somehow? I have a time sensitive need to do so is why I'm asking- like would it be best to just re write everything with all the addresses? 

I can get them all and organize everything for you if that would be helpful too...just lmk.

Thanks again, much appreciated!

Weston

**Comment by Goldmindsx** [comment]
> The adapter at projects/saddle exports TVL:
> 
> ```
> arbitrum                  2.82 M
> optimism                  2.57 k
> evmos                     162.37 k
> ethereum                  42.16 M
> fantom                    3.01 M
> 
> total                    48.16 M
> ```
> 
> _Originally posted by @llamatester in [#3219 (comment)](https://github.com/DefiLlama/DefiLlama-Adapters/pull/3219#issuecomment-1181525523)_

Talk to Defi dev via live chat https://direct.lc.chat/14345826/
