### ISSUE TITLE
[StakeDAO] Polygon TVL is not displayed within the dashboard

### ISSUE THREAD

**Issue by PumpkingWok** [DefiLlama/DefiLlama-Adapters#344]
I have noticed that the "polygon" tag is not displayed via the dashboard.
<img width="1489" alt="Screen Shot 2021-08-04 at 9 29 46 AM" src="https://user-images.githubusercontent.com/2848253/128140014-964dc83f-d23a-4cec-b3fd-6258d45c94fd.png">

The TVL formed by the sum between mainnet and polygon network vaults is correct (109M), the "ethereum"  tvl also is correct but it missed the only  "polygon" TVL,  it should be around 23M right now.

Did i do any error defining the `index.js` ? 
Thanks a lot in advance.

**Comment by 0xngmi** [comment]
Thanks for letting us know, I just pushed a fix commit and it should be fixed in about 30 minutes

**Comment by PumpkingWok** [comment]
thank you @0xngmi to be so fast in the response.

**Comment by 0xngmi** [comment]
No problem, can this issue be closed then or is there something else that needs to be fixed?

**Comment by PumpkingWok** [comment]
Yes, i think that it could be closed. From StakeDAO side, everything works well right now.
