### ISSUE TITLE
Clearpool Total Liquidity Provided instead of TVL.

### ISSUE THREAD

**Issue by zolotokrylin** [DefiLlama/DefiLlama-Adapters#3502]
Hi DefiLlama maintainers 👋 
Vadim from Clearpool is here.

**We have spotted an issue: our borrowing is not based on collateral.** 

Our protocol has a different and innovative model, which is based on un-collateralized loans. In other words, Clearpool is a decentralized marketplace for unsecured institutional capital. It allows institutions to borrow funds from a decentralized network of lenders without the need for collateral.

Can we update our TVL to reflect the actual value locked? You can see it here: https://app.clearpool.finance/lend

![image](https://user-images.githubusercontent.com/1125014/183845381-72d07f68-288c-4635-8f20-8fe8b5d99c4c.png)

**Comment by g1nt0ki** [comment]
hi @zolotokrylin I am looking into this now

**Comment by g1nt0ki** [comment]
@zolotokrylin https://github.com/DefiLlama/DefiLlama-Adapters/pull/3521 I have fixed it here, have omitted permissioned pool.

**Comment by zolotokrylin** [comment]
@g1nt0ki awesome! when can we see the reflection on production?

**Comment by g1nt0ki** [comment]
it is visible in the UI now, trying to fix historical data now.

**Comment by g1nt0ki** [comment]
https://defillama.com/protocol/clearpool?hideMcapChart=true

**Comment by zolotokrylin** [comment]
@g1nt0ki did you guys managed to have a look into historical data problem?
And thanks again for your fix!

**Comment by g1nt0ki** [comment]
it is fixed now: https://defillama.com/protocol/clearpool?hideMcapChart=true

**Comment by zolotokrylin** [comment]
Amazing! Thank you
