### ISSUE TITLE
Bifrost chain page seeming not to be working for some reason.

### ISSUE THREAD

**Issue by killbond007** [DefiLlama/DefiLlama-Adapters#3558]
Hello DefiLlama maintainers

Bifrost chain page doesn't working (but working in https://defillama.com/protocol/bifrost)

<img width="1270" alt="Screenshot 2022-08-15 at 23 35 21" src="https://user-images.githubusercontent.com/22051991/184722615-5d222ea9-d0c5-426a-aec3-fda2daa4d918.png">

https://defillama.com/chain/Bifrost

**Comment by dtmkeng** [comment]
# brave
<img width="1414" alt="image" src="https://user-images.githubusercontent.com/11234402/185027373-ba25bd44-8acd-4b62-902a-290adafeb380.png">

**Comment by killbond007** [comment]
> # on brave browser
> <img alt="image" width="1414" src="https://user-images.githubusercontent.com/11234402/185027373-ba25bd44-8acd-4b62-902a-290adafeb380.png">


some problem in https://defillama.com/chains/Parachain and https://defillama.com/chain/Bifrost . I don't know why

<img width="1532" alt="Screenshot 2022-08-17 at 09 39 34" src="https://user-images.githubusercontent.com/22051991/185062441-3ac2115a-f021-48fe-9113-0fffb91055e1.png">

**Comment by g1nt0ki** [comment]
@killbond007 I think you need to enable liquid staking option in the filter
![image](https://user-images.githubusercontent.com/99907941/185091500-13bd0456-812e-49eb-b098-692262aebd48.png)
