### ISSUE TITLE
A few requests for orbit bridge

### ISSUE THREAD

**Issue by rlekdms** [DefiLlama/DefiLlama-Adapters#3598]
@g1nt0ki 
Hello DefiLlama maintainers.
Thanks for listing our product. But there are a few changes I want.

1. Our Product's name is "Orbit Bridge" not "Orbit Chain". Please change it.
2. Please include ORC tvl in the total tvl. The project's native token is oORC that bridge from ethereum to orbit chain. ORC is the ethereum based token and has its own price.

**Comment by g1nt0ki** [comment]
it is fixed: https://defillama.com/protocol/orbit-bridge
