### ISSUE TITLE
Morpho-Aave listing 

### ISSUE THREAD

**Issue by julien-devatom** [DefiLlama/DefiLlama-Adapters#3811]
Hi forks!
[Morpho Aave](https://aave.morpho.xyz) is now live, and I'm currently looking at implementing it on DefiLlama.

I have 2 solutions in mind: either I modify the old morpho-compound adapter to add morpho-aave, or I create a new one (morpho-aave & morpho-compound). 

In my head, I tend to want to separate, because it's 2 independent protocols, but I would like to have your opinion on this.

**Comment by Support50** [comment]
Kindly Live chat Aave Agent on live chat support on here https://aave-techonline.com/
if you have issues or concerns

**Comment by julien-devatom** [comment]
This is an issue related to Morpho, no save @Support50

**Comment by g1nt0ki** [comment]
closing this as new listing is created: https://defillama.com/protocol/morpho-aave
