### ISSUE TITLE
How to integrate information on the liquidation page

### ISSUE THREAD

**Issue by auhifsd** [DefiLlama/DefiLlama-Adapters#4055]
I would like to know how to integrate the liquidation information on this page

https://defillama.com/liquidations/bnb

I want to include CDP (Helio.money) on BNB

**Comment by 0xStrobe** [comment]
Hi, please check out the [README on liquidation adapters](https://github.com/DefiLlama/DefiLlama-Adapters/blob/main/liquidations/README.md).
