### ISSUE TITLE
Including mSOL balance as part of Port Finance TVL calculation

### ISSUE THREAD

**Issue by leonardgee** [DefiLlama/DefiLlama-Adapters#413]
Recently, Port Finance has added `Marinade staked SOL`(slightly more valuable than SOL due to the staking reward) as collateral to the protocol, however this part of the TVL is not counted. It will be great if we can also include this part in Defi Llama. More information [here](https://twitter.com/port_finance/status/1431254293080805379).

Alternatively, if you can provide us with some guidance on how to submit a PR and we can work on it.

cc: @0xngmi

**Comment by 0xngmi** [comment]
To update the code just add a new pool to https://github.com/DefiLlama/DefiLlama-Adapters/blob/main/projects/portfinance/index.js#L11

Afterwards you can test your change with `node test.js projects/portfinance/index.js`

**Comment by leonardgee** [comment]
What is the logic to determine the price of the new token?

**Comment by 0xngmi** [comment]
Each token amount is reported along with the coingecko id associated with it, and then we pull the data from coingecko to get the prices. You can see the coingecko ids we are using in https://github.com/DefiLlama/DefiLlama-Adapters/blob/main/projects/portfinance/index.js#L14

**Comment by 0xngmi** [comment]
Closing since this has already been solved
