### ISSUE TITLE
Yieldly TVL Not Combined

### ISSUE THREAD

**Issue by FoxThe** [DefiLlama/DefiLlama-Adapters#421]
Yieldly Staking and Algorand Values are not combined in TVL. 
![image](https://user-images.githubusercontent.com/89874712/131573075-3f9caf0d-7ddd-4dcb-99a8-8f09c5a633ad.png)

**Comment by 0xngmi** [comment]
This is by design

**Comment by FoxThe** [comment]
Thanks for the quick response. Is there any specific reason? Several of the other protocols have it combined? Just doesn't make sense to me why only Algorand Staking is part of the TVL and not YLDY staking where there is another $40 odd million, therefore, not effectively showing how much is locked up in this DeFi suite. 

Other protocols have them combined?
![image](https://user-images.githubusercontent.com/89874712/131619306-126777b5-dfc5-45e3-bfe2-b5ad7c5e3f09.png)
![image](https://user-images.githubusercontent.com/89874712/131619353-4192ee0c-ddfb-4189-94b3-bb9c6f7fbe24.png)

Am i missing something?

**Comment by 0xngmi** [comment]
Other protocols don't have it combined, what we combine is the TVL across chains, but we don't add staking nor poo2 into the TVL. If you see a protocol for which we are combining TVL into staking let us know and we'll fix it.

You can see this in the case of sushi, which you linked, there's >3bn sushi locked in xSUSHI, which you could consider to be staking, however we don't add those billions onto the main TVL

**Comment by FoxThe** [comment]
Ah makes sense, your explanation is much appreciated.

**Comment by 0xngmi** [comment]
For some other examples of this where we display staking but don't include it you could see aave or pancakeswap

**Comment by 0xngmi** [comment]
Adding staking or pool2 into the main protocol TVL is configurable through the menu on the top right, they are just disabled by default

![image](https://user-images.githubusercontent.com/80541789/131620460-6a7ebaab-1a54-43a5-955d-ef917d84f1be.png)
