### ISSUE TITLE
API for historical value is returning wrong value 

### ISSUE THREAD

**Issue by hyossid** [DefiLlama/DefiLlama-Adapters#4264]
Hi, this is Sidney from ALEX team. 
https://defillama.com/protocol/alex?denomination=USD

I just swung by Defillama adapters page and found out that our historical token TVL is showing wrong values.

<img width="1121" alt="image" src="https://user-images.githubusercontent.com/34973707/195261273-98ba3545-7547-4468-b820-bc1706cff3aa.png">
https://defillama.com/protocol/alex?denomination=USD

Data points for this graph is coming from below endpoint

<img width="490" alt="image" src="https://user-images.githubusercontent.com/34973707/195261499-e1b5bec4-9873-4b61-b09b-48d10ef3df72.png">

Currently, we do not handle tether, so it seems like there is a bug on this endpoint, probably fetching wrong values in your DB. 

Would you mind please checking?

Regards,
Sidney

**Comment by g1nt0ki** [comment]
hi @hyossid you dont have tether, we just use it internally to represent us dollars, we have set [`misrepresentedTokens` flag ](https://github.com/DefiLlama/DefiLlama-Adapters/blob/main/projects/alexlab/index.js#L39)as true, this means, token breakdown is wrong, not sure why it is even showing up in the UI, it doesnt show up in my browser when I just tried
