### ISSUE TITLE
$0 TVL for Swaap Protocol

### ISSUE THREAD

**Issue by borelien** [DefiLlama/DefiLlama-Adapters#4346]
Hi folks!
TVL values are $0 since October 4th: https://defillama.com/protocol/swaap
Any idea on what causes that issue?

**Comment by g1nt0ki** [comment]
hi @borelien there was a bug in determining block, essentially we were looking at history in the past.


I have fixed the bug here: https://github.com/DefiLlama/DefiLlama-Adapters/commit/d60aa8c41d0ba39234313d7696eabc543082c22a and fix the tvl chart
