### ISSUE TITLE
Milkomeda A1 is classified as a rollup, but TVL is not yet assigned to Algorand. It inherits from Algorand's security unlike C1

### ISSUE THREAD

**Issue by cysecB** [DefiLlama/DefiLlama-Adapters#4487]
Security of the Milkomeda Algorand Rollup: https://medium.com/@milkomedafoundation/security-of-the-milkomeda-algorand-rollup-77e6ea784ea6

The TVL of A1 would have to be counted to Algorand's TVL accordingly

**Comment by g1nt0ki** [comment]
@cysecB we dont count Optimism/Arbitrum tvl as part of Ethereum tvl either

**Comment by cysecB** [comment]
@g1nt0ki However, there is the option to display Ethereum's TVL aggregated with L2 TVL. A1 should be subordinated to Algorand like Optimism to Ethereum

**Comment by cysecB** [comment]
A1 is now assigned to Algorand. Thanks
