### ISSUE TITLE
List Algodex on DefiLlama's DEX category

### ISSUE THREAD

**Issue by hasyminh** [DefiLlama/DefiLlama-Adapters#4530]
We can do it either way:
1. Open PR on https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/volumes using Tinyman's endpoint to get total volume per day https://github.com/DefiLlama/DefiLlama-Adapters/blob/main/volumes/adapters/tinyman/index.ts
OR
2. Apply on https://github.com/DefiLlama/DefiLlama-Adapters/blob/main/volumes/adapters/sunswap/index.ts if having historical data.

**Comment by ponury1990** [comment]
👍

**Comment by g1nt0ki** [comment]
closing this as due to lack of activity
