### ISSUE TITLE
MuesliSwap historical Volume is missing

### ISSUE THREAD

**Issue by MuesliSwapTeam** [DefiLlama/DefiLlama-Adapters#4540]
Even though the added volume adapter supports time travel, the volume graph on DeFiLlama only shows the volume for one day (since we added this adapter). This is really unfortunate to be missing (about 1 year of data, that is actually returned by the endpoint). Is there a way we can fix this?

**Comment by 0xngmi** [comment]
i believe this is now fixed, is all good?
