### ISSUE TITLE
Something wrong in iZUMi LiquidBox tvl

### ISSUE THREAD

**Issue by LpcAries** [DefiLlama/DefiLlama-Adapters#4556]
I pull the latest code and ran the test. The pool2 tvl should be 33+M, but the website only shows 440k.
<img width="335" alt="2022-11-05 17 45 19" src="https://user-images.githubusercontent.com/101619245/200114136-10dd71f7-ea7f-42fa-bad0-2b8b2784da34.png">
<img width="1159" alt="2022-11-05 17 48 19" src="https://user-images.githubusercontent.com/101619245/200114142-e431089c-0560-4b93-9f87-08b064a0a539.png">

**Comment by g1nt0ki** [comment]
it looks fixed now: https://defillama.com/protocol/iziswap
