### ISSUE TITLE
Stride TVL not showing up on Cosmos page

### ISSUE THREAD

**Issue by asalzmann** [DefiLlama/DefiLlama-Adapters#4568]
**Context**
We recently added a [Stride adapter](https://github.com/DefiLlama/DefiLlama-Adapters/pull/4551). Stride TVL is showing up [here](https://defillama.com/protocol/Stride). Note, the url for this is /protocol/Stride.

We should be roughly the ~10th largest Cosmos app on [this page](https://defillama.com/chains/Cosmos), however it displays our TVl as 0. The issue is that it links to [/chains/Stride](https://defillama.com/chain/Stride), which does not exist.

**Question**
How can we fix this? Do we need to create a separate adapter?

**Comment by g1nt0ki** [comment]
hi, checked with the team, the issue why 'Stride' chain page is not showing up is, you dont have protocols with default tvl (tvl  from Yield/Liquid Staking/RWA not counted by default)

To display Stride tvl in Cosmos page: enable 'Liquid Staking' filter
![image](https://user-images.githubusercontent.com/99907941/200679706-45089bb0-2af5-4a8a-bc4a-bad15b7af0b1.png)

**Comment by g1nt0ki** [comment]
just checked if you enable liquid staking filter, the chain page also shows up: 
![image](https://user-images.githubusercontent.com/99907941/200680078-1c7bf12d-ab9b-4f0e-bbf7-ca086a6500e6.png)

**Comment by asalzmann** [comment]
The Stride chain _is_ displayed on this page though, at the bottom
<img width="1057" alt="Screen Shot 2022-11-08 at 5 34 25 PM" src="https://user-images.githubusercontent.com/1331345/200690684-0afac35d-cdb9-465f-9028-f81af1e4fa89.png">

I also think this is the wrong way to display the page by default. In Cosmos, each chain is an application, so this is similar to displaying a list of dApps on Ethereum and arbitrarily excluding liquid staking from the list. Can it please be included by default?

**Comment by g1nt0ki** [comment]
I am sorry, but this is the same rule we have fo all chains/protocols.

Does stride chain tvl not change when user enables 'Liquid Staking' filter

**Comment by asalzmann** [comment]
@0xngmi can you please take a look at this? Stride *only* does liquid staking, as an app chain, so the page that shows $0 TVL will always show that, unless liquid staked tokens are included. We've had Stride users reach out and mention this confusing UX, thinking it's a bug on DefiLlama. I don't understand the rationale for not counting liquid staked tokens.
