### ISSUE TITLE
Cardano volume of MuesliSwap DEX is not showing anymore

### ISSUE THREAD

**Issue by MuesliSwapTeam** [DefiLlama/DefiLlama-Adapters#4656]
After commit 11fcb6f3b2410fa0f68a4a0f4ae2b6351892e923, the volume for MuesliSwap was correctly showing for both the Milkomeda version and the Cardano Mainnet version of the exchange. The volume is not showing anymore, even though the endpoints still work. The only change since the initial commit is ed14d230da2d54cff3e3f59569d36c32336f2eaf but the volume was correctly showing last week still.

**Comment by dtmkeng** [comment]
we move the volume adapter to new repo if you have a new change, you can open pr update on this repo https://github.com/DefiLlama/adapters/tree/master/dexs/muesliswap

**Comment by MuesliSwapTeam** [comment]
Thanks for the quick reply! Result looks good :+1:
