### ISSUE TITLE
Add Stormswap Finance

### ISSUE THREAD

**Issue by Storm224** [DefiLlama/DefiLlama-Adapters#479]
Twitter:- https://twitter.com/StormSwap_Fi

Audited By paladin:- https://paladinsec.co/projects/stormswap-finance/

Website:- https://stormswap.finance/

Logo:- https://pbs.twimg.com/profile_images/1431363725429248005/nFiYZ2xO_400x400.png

TVL:-13.5M

Chain:- AVALANCE

Coingecko ID (so your TVL can appear on Coingecko): (https://api.coingecko.com/api/v3/coins/list)  -Storm Token

Description:- StormSwap is an upcoming sustainable decentralized yield farming & yield aggegrator protocol powered by Avalanche 🔺. Our focus is to provide a safe yield farming experience for our investors who are willing to support us on our journey to becoming one of Avalanche best defi protocols available.

Category:- Yield Farming

Token Ticker:-  STORM

https://cchain.explorer.avax.network/tokens/0x6AFD5A1ea4b793CC1526d6Dc7e99A608b356eF7b/token-transfers

Oracle used (Chainlink/Band/API3/TWAP or any other that you are using):
forkedFrom (Does your project originate from another project):

**Comment by 0xngmi** [comment]
Hey, we would appreciate if you could me a Pull Request providing a script that we can use to pull your TVL

**Comment by Storm224** [comment]
Hey, you mean this https://www.coingecko.com/en/coins/storm-token. Let me know if it's gonna work on not.

**Comment by 0xngmi** [comment]
No, we need a script that calculates tvl
