### ISSUE TITLE
Add new DEX on TON to monitoring

### ISSUE THREAD

**Issue by DeFiTON** [DefiLlama/DefiLlama-Adapters#4975]
**Good afternoon.** Can add +1 more DEX on the TON blockchain. Thanks!

Project site:
- https://tegro.finance

Documentation and source code:
- https://github.com/orgs/TegroTON/repositories

Roadmap and information:
- https://tegro.gitbook.io/en/dex/

**Comment by g1nt0ki** [comment]
@DeFiTON  am struggling to query for pool/token list from ton chain, can you help me with that part?

**Comment by g1nt0ki** [comment]
@DeFiTON how do you form this pair information here? https://api.tegro.finance/pairs
Can you check with others in your team as to how to fetch this directly from the chain? I would like limit dependency on 3rd party services as much as possible
