### ISSUE TITLE
Add more DEX on TON to monitoring

### ISSUE THREAD

**Issue by DeFiTON** [DefiLlama/DefiLlama-Adapters#4989]
Good afternoon. Can add one new DEX on the TON blockchain. Thanks!

Project site:

- https://dedust.io/dex/swap

Other info and documentation:
- https://coinmarketcap.com/exchanges/dedust/

Pools:
- https://dedust.io/pools

**Comment by g1nt0ki** [comment]
@DeFiTON I am struggling with implementing adapter for these? how does one query pair information for these two, can you help me?
