### ISSUE TITLE
Show total TVL for LunaFi

### ISSUE THREAD

**Issue by l-fi** [DefiLlama/DefiLlama-Adapters#5028]
@g1nt0ki  
Not sure why we have made pool2 and staking separately. We want to show the entire amount of 172k as TVL.
Currently, it appears a bit different to what we imagined:
We have 4 staking pools for different tokens LFI, USDC, WBTC and WETH
We call them House Pools. USDC House Pool, WETH House Pool, WBTC House Pool and LFI House Pool we just call Staking pool.

We can either show them as different house pools or just the total TVL.

<img width="660" alt="Screenshot 2023-01-11 at 15 52 08" src="https://user-images.githubusercontent.com/92627901/211915978-fabd0aa4-7973-4c51-963b-c7b5981eafce.png">

**Comment by g1nt0ki** [comment]
I split because of this: https://docs.llama.fi/list-your-project/what-to-include-as-tvl 
I dont want other protocols to complain that we are treating you differently
