### ISSUE TITLE
Update Level.finance audit and fork

### ISSUE THREAD

**Issue by 20xlevel** [DefiLlama/DefiLlama-Adapters#5051]
Hi, I'm 20xlevel from Level Team. I want to update some new Audit and Fork information.

Can you please update this on your website?
Thank you!

---

##### List of audit links if any:
https://obeliskauditing.com/audits/level-finance-core
https://obeliskauditing.com/audits/level-finance-trading

##### forkedFrom (Does your project originate from another project):
No

**Comment by 20xlevel** [comment]
We take inspiration from GMX's work but do not borrow any piece of their code. Besides, we introduced many enhancements. Therefore, people want us to stop referring to our protocol as a GMX fork so they don't get confused.

**Comment by Define101** [comment]
Hello 20xlevel
Thank you for the PR, we have updated the audit links, should be live within 1 hour
Have a great day
