### ISSUE TITLE
Kujira Bow & Black Whale Showing as Double-Counted TVL

### ISSUE THREAD

**Issue by MikeR808** [DefiLlama/DefiLlama-Adapters#5064]
The recent PR https://github.com/DefiLlama/DefiLlama-Adapters/pull/5062 has resulted in a drop of TVL for Kujira due to Bow & Black Whale now being considered as double counted TVL.

Neither protocol uses double counting in its methodology to calculate TVL. Both use market making strategies on Kujiras FIN to provide yield to depositors but the TVL calculation does not include any of the assets deposited to FIN orderbook and only assets that remain in the vault which are counted nowhere else.

Further, any staking of LP tokens is also excluded from Bow.

I could not find the right config to create a PR to remove the double count TVL flag for these.

**Comment by g1nt0ki** [comment]
closing this as it looks fixed to me: https://defillama.com/chain/Kujira
