### ISSUE TITLE
Update Protocol Information

### ISSUE THREAD

**Issue by wshino** [DefiLlama/DefiLlama-Adapters#5097]
Recently I created [the PR](https://github.com/DefiLlama/DefiLlama-Adapters/pull/5057) to apply Predy version 3. This PR has already been merged. Thank you for your work. 

But [this info page](https://defillama.com/protocol/predy-finance), it seem `Protocol Information` haven't updated into V3. I'd like to update only this info. The below text is identical to what is already in the merged PR. Thanks.

**Protocol Information**
The core of Predy v3 is the Tripartite Lending Protocol(TLP) as the middle protocol to handle ETH, USDC, and Uniswap LPT (applicable to any Token pair and its Uniswap LPT) to represent the status of lending as an perpetual option (LP fees = option premiums). Uniswap achieved path independence for total K by using only token-pair quantities, which Predy v3 inherits.
The measurement of the position's value against the debt is the key of lending protocol, and it maintains a positive value with the certain volatility of the underlying asset price, where It's verifiability and finality bring extension that other protocols have not been able to achieve due to external dependencies and administrative privileges.
Built on Arbitrum.

**Comment by g1nt0ki** [comment]
I have fixed it here: https://github.com/DefiLlama/defillama-server/commit/4dee5b58e8a29157cb42348f88bebbeb1fb744a6
