### ISSUE TITLE
Add TON as core asset on TON blockchain

### ISSUE THREAD

**Issue by SlavikBaranov** [DefiLlama/DefiLlama-Adapters#5226]
Currently ston.fi reports TON asset in the pools as address `EQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAM9c` this is equivalent to ethereum NULL address (`0x0000000000000000000000000000000000000000`). 

The TVL of ston.fi is incorrectly reported as $400k whereas it is around $570k.
 
Please add ton:EQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAM9c as core asset in TON blockchain and make it available at URL: https://coins.llama.fi/prices/current/ton:EQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAM9c

**Comment by g1nt0ki** [comment]
fixed it here: https://github.com/DefiLlama/defillama-server/commit/dfed0c09b7c38635f9aa904db02450825e3bfa57
