### ISSUE TITLE
Duplicated hallmark of FTX collapse event on Amulet Main Page

### ISSUE THREAD

**Issue by yym-mtrlabs** [DefiLlama/DefiLlama-Adapters#5310]
https://github.com/DefiLlama/DefiLlama-Adapters/pull/5279

Checked the updated page at https://defillama.com/protocol/amulet , seems on the merged page there are duplicated hallmark of FTX collapse. Understand that this is because the same hallmark is added in both of the sub page, may I check whether its possible to keep only one in the merged page?

**Comment by g1nt0ki** [comment]
@mintdart can something be done about this?

**Comment by mintdart** [comment]
fixed! https://defillama.com/protocol/amulet

**Comment by yym-mtrlabs** [comment]
Thanks for the help! @mintdart @g1nt0ki
