### ISSUE TITLE
We created a new dex on polygon (Matic) - neopin project

### ISSUE THREAD

**Issue by yepp4you** [DefiLlama/DefiLlama-Adapters#5461]
We created a new dex on polygon (Matic).

The newly deployed contract information on polygon is shown below.

factory: '0x1289ae78422b94414c1F827C534a1fE8E31E71Aa'
router02: '0x511C180A2E69cA700CeA66f609B8a2357f5980eC'
WMATIC(WETH): '0xFD28c7ceA3c50a060cB4c0059E453C6D4DD9829d'
NPT(Multichain NPT): '0x306ee01a6bA3b4a8e993fA2C1ADC7ea24462000c'
MATIC-NPT (LP Token): '0x2Dae48CFEC770884A2DBC43b43AffB2eCF8d41b2'

**Comment by yepp4you** [comment]
We created a new dex on polygon (Matic).
check please
@g1nt0ki

**Comment by boomer2** [comment]
@g1nt0ki kindly ping you

**Comment by g1nt0ki** [comment]
it is fixed: https://github.com/DefiLlama/DefiLlama-Adapters/commit/3a80784af9032eb5b902137b4ef3b9906f086ec3
