### ISSUE TITLE
Add ReHold Audit

### ISSUE THREAD

**Issue by bifot** [DefiLlama/DefiLlama-Adapters#5527]
Hi, we've been passed an audit from PeckShield.

1. https://defillama.com/protocol/rehold
2. https://github.com/peckshield/publications/blob/master/audit_reports/PeckShield-Audit-Report-ReHold-v1.0.pdf

Could we add this link to our page, please?

Thank you!

**Comment by Define101** [comment]
Thanks
Should be live within 1 hour

**Comment by bifot** [comment]
Thank you! Currently, it's not shown. Is it ok?
