### ISSUE TITLE
MIND Games tvl mix-up on website

### ISSUE THREAD

**Issue by thatborghugh** [DefiLlama/DefiLlama-Adapters#5528]
Following the updates made for MIND Games on Arbitrum we noticed that the reported tvl for _WBTC_ and _WETH_ are swapped on the TVL charts.

The adapter correctly reports:
```
--- arbitrum ---
WETH                      844.65 k
WBTC                      261.53 k
GMX                       212.82 k
USDC                      208.09 k
USDT                      139.23 k
```

while the site is showing:
![image](https://user-images.githubusercontent.com/109151284/223694301-5755fa46-0274-4eb1-a76c-267aff3422f7.png)

Please advise if something is needed from our end to fix this issue.
Thank you!

**Comment by g1nt0ki** [comment]
it was caused by a bug, we should not be showing token breakdown in the first place.

**Comment by g1nt0ki** [comment]
I have fixed it
