### ISSUE TITLE
tetuBal pool data doesn't  show accurate values

### ISSUE THREAD

**Issue by 0xMertt** [DefiLlama/DefiLlama-Adapters#5613]
<img width="1026" alt="Screenshot 2023-03-17 at 10 59 14" src="https://user-images.githubusercontent.com/97477265/225873124-89dfb1d9-0133-48d3-a7d6-7f5f76862b11.png">

<img width="1503" alt="Screenshot 2023-03-17 at 11 00 33" src="https://user-images.githubusercontent.com/97477265/225873406-a77c989c-b337-4fe4-82ab-2b10d9102aee.png">

I'm observing a discrepancy between the data for the tetubal pool on Defilamma and the Balancer website.

**Comment by g1nt0ki** [comment]
closing issue as old and hoping it has fixed itself
