### ISSUE TITLE
Lido for Solana is using the amount at the start of the epoch, not the current amount

### ISSUE THREAD

**Issue by ruuda** [DefiLlama/DefiLlama-Adapters#562]
Hi, thanks for including Lido for Solana in Defi Llama!

I noticed that to get Lido's SOL balance, you are using the internal exchange rate:

https://github.com/DefiLlama/DefiLlama-Adapters/blob/e57e1507666c7d1c1bda267125fb9181199dabfc/projects/lido/index.js#L43

This value is updated once per epoch (an epoch is roughly 2.5 days), so depending on when you query it, it may be outdated by 2.5 days. If you want to know the current balance, you should instead take the sum of [`validator.stake_accounts_balance`](https://github.com/DefiLlama/DefiLlama-Adapters/blob/e57e1507666c7d1c1bda267125fb9181199dabfc/projects/lido/Lido.js#L159) over all validators, and add to that the balance of the reserve ([`3Kwv3pEAuoe4WevPB4rgMBTZndGDb53XT7qwQKnvHPfX`](https://docs.solana.lido.fi/deployments#mainnet-beta)). That would ensure that deposits and withdrawals are reflected immediately, without having to wait for the start of the next epoch.

For reference, [the Rust version of this computation is here](https://github.com/ChorusOne/solido/blob/a601d3a8e3aabd4056ac7b14d8534b197706712e/program/src/state.rs#L563-L574).

**Comment by 0xngmi** [comment]
Could you submit a PR for it? That'd help a lot

**Comment by JEasterman** [comment]
@ruuda I jumped on this one for some practice. Does my methodology look correct?

Old Calculation: 79.48 M
New Calculation: 79.75 M
Lido Website: 80.84 M (SOL price feed differential?)

**Comment by 0xngmi** [comment]
In case more people make the same mistakes I did, the reason why I implemented it this way was because I followed the instructions on https://docs.solana.lido.fi/development/frontend-integration/#useful-nuggets
