### ISSUE TITLE
Defi Llama project page crashing on open.

### ISSUE THREAD

**Issue by spaceforce-dev** [DefiLlama/DefiLlama-Adapters#58]
A issue has arisen on our project page (MANTRA DAO), 

we didn't change any code, it seems like might be a front end issue.

See image below.

<img width="621" alt="Screen Shot 2021-03-15 at 10 36 14 am" src="https://user-images.githubusercontent.com/71380821/111088313-b8ed5d00-857a-11eb-99b5-690bc113ffcd.png">

Thanks for the help.

**Comment by 0xngmi** [comment]
Thanks for reporting, looking into it.

**Comment by 0xngmi** [comment]
I've already pushed a change that fixes the issue, it should be live in a few mins.

> we didn't change any code, it seems like might be a front end issue.

Indeed it was, the problem was that the frontend didn't handle well the cases where a project has no category.

**Comment by 0xngmi** [comment]
It should be working fine now, let us know if anything else pops up!
