### ISSUE TITLE
[GENS] Broken Cardanoscan link

### ISSUE THREAD

**Issue by 4TT1L4** [DefiLlama/DefiLlama-Adapters#5893]
**Problem:**
 - The [View on Cardanoscan](https://cardanoscan.io/token/dda5fdb1002f7389b33e036b6afee82a8189becb6cba852e8b79b4fb) is broken for the [Genius Yield](https://defillama.com/protocol/genius-yield) project. Clicking the link leads to a `Token not found` error message:

![image](https://user-images.githubusercontent.com/2914096/231351922-a7138a20-5e22-4317-a425-497236116e8b.png)

The currently used URL only includes the policy ID, but the asset name should be also part of the Cardano scan URL:

Current, broken 'View on Cardanoscan' link:

https://cardanoscan.io/token/dda5fdb1002f7389b33e036b6afee82a8189becb6cba852e8b79b4fb
Incorrect URL Structure: https://cardanoscan.io/token/{policy-ID}

This is not correct, since the asset name is missing from the end of the URI.

**Solution:**
 - Make sure to use the correct URL for the GENS token and append the asset name to the Cardanoscan token url.

Expected Cardano Scan Token URL Structure: https://cardanoscan.io/token/{policy-ID}{asset-Name}

GENS Policy ID: [dda5fdb1002f7389b33e036b6afee82a8189becb6cba852e8b79b4fb](https://cardanoscan.io/tokenPolicy/dda5fdb1002f7389b33e036b6afee82a8189becb6cba852e8b79b4fb)
GENS Asset Name: 0014df1047454e53

https://cardanoscan.io/token/dda5fdb1002f7389b33e036b6afee82a8189becb6cba852e8b79b4fb0014df1047454e53
Correct URL Structure: https://cardanoscan.io/token/{policy-ID}{asset-Name}

**Comment by 4TT1L4** [comment]
Some other Cardano Project like MüsliSwap or MinSwap use the token URI and it is actually working fine for those.

MinSwap:
https://defillama.com/protocol/minswap
https://cardanoscan.io/token/asset1d9v7aptfvpx7we2la8f25kwprkj2ma5rp6uwzv [OK]

MüsliSwap:
https://defillama.com/protocol/muesliswap
https://cardanoscan.io/token/8a1cfae21368b8bebbbed9800fec304e95cce39a2a57dc35e2e3ebaa.MILK [OK]

GeniusYield:
https://defillama.com/protocol/genius-yield
https://cardanoscan.io/token/dda5fdb1002f7389b33e036b6afee82a8189becb6cba852e8b79b4fb [NOK! Broken!] 

The issue seems to be that the policy ID is passed in the case of Genius Yield. But it should be the asset fingerprint or the policy ID and the asset name concatenated:

GENS Asset Fingerprint:
asset1266q2ewhgul7jh3xqpvjzqarrepfjuler20akr
https://cardanoscan.io/token/asset1266q2ewhgul7jh3xqpvjzqarrepfjuler20akr [OK]

**OR**

```
GENS policyId + GENS assetName = 
dda5fdb1002f7389b33e036b6afee82a8189becb6cba852e8b79b4fb 
 + 
0014df1047454e53 
 =
dda5fdb1002f7389b33e036b6afee82a8189becb6cba852e8b79b4fb0014df1047454e53
```
https://cardanoscan.io/token/dda5fdb1002f7389b33e036b6afee82a8189becb6cba852e8b79b4fb0014df1047454e53 [OK]

The current broken link for Genius Yield is using only the policy ID:
https://cardanoscan.io/token/dda5fdb1002f7389b33e036b6afee82a8189becb6cba852e8b79b4fb  [BROKEN]

**Comment by 0xngmi** [comment]
looks like this was fixed here https://github.com/DefiLlama/defillama-server/commit/5608e5bd8fbfb7c67c60d0f942fec5b47e70944d

**Comment by 4TT1L4** [comment]
@0xngmi 
> looks like this was fixed here https://github.com/DefiLlama/defillama-server/commit/5608e5bd8fbfb7c67c60d0f942fec5b47e70944d

Yupp. It is fixed. Now the Genius Yield Project's Cardanoscan link leads to the expected page. The same goes for the two other projects; no regression could be found.

Thank you for the notice. I am closing this issue. :-)👍
