### ISSUE TITLE
API missing chainTvls for makerdao

### ISSUE THREAD

**Issue by tadbooch** [DefiLlama/DefiLlama-Adapters#611]
Hello, when trying this api link, https://api.llama.fi/protocol/makerdao I see chainTvls section is missing data. The data show up when I try to download excel from site. 

I see same issue with few others too - e.g. convex-finance, instadapp.

Can you please take a look? 

Thanks,

![image](https://user-images.githubusercontent.com/67764801/135492244-c77b2bd5-19ce-438e-b65e-296984f8adae.png)

**Comment by tadbooch** [comment]
I also see similar behavior/issue with this API endpoint where chainTvls field is missing data --> https://api.llama.fi/protocols

Thanks again,

![image](https://user-images.githubusercontent.com/67764801/135495692-942aaac4-aeaf-4fe7-9100-cd1d12023d01.png)

**Comment by 0xngmi** [comment]
that happens when a protocol is on a single chain, putting data on chainTvls would mean repeating the data already available so we don't do it

**Comment by tadbooch** [comment]
Got it, thanks. Was expecting chainTvls so that's it's easier to sum but understand if its by design.
Thanks,

**Comment by 0xngmi** [comment]
Somebody else complained about the same issue so I'll do it for https://api.llama.fi/protocol/makerdao

About /protocols idk if I should apply that change, I could but it will increase the time it takes to build and it's on the critical path so unsure about it
