### ISSUE TITLE
Why? this doesn't look like the right token for price feed at all

### ISSUE THREAD

**Issue by gaspare100** [DefiLlama/DefiLlama-Adapters#6170]
https://github.com/DefiLlama/DefiLlama-Adapters/blob/648861136a6f9f7aca0707e6c7aa97414175e04a/projects/funbear/index.js#L1

**Comment by Define101** [comment]
What is the problem?
What should be the correct token address?

**Comment by gaspare100** [comment]
i can't find anywhere that the address provided later for staking on kava is actually in any way linked to the one on ethereum used for price tracking

**Comment by g1nt0ki** [comment]
> i can't find anywhere that the address provided later for staking on kava is actually in any way linked to the one on ethereum used for price tracking

you are right, sorry it took us so long to address this, we have fixed it
