### ISSUE TITLE
[Neopin] deployed new Dex on ethereum and updated stake address on Klaytn

### ISSUE THREAD

**Issue by yepp4you** [DefiLlama/DefiLlama-Adapters#6225]
@g1nt0ki 

There was an update regarding staking on KLAYTN, the following addresses have been added.
We would appreciate it if you could add the address below.

Contract  address1 : 0xDa664b81C13b050F9b0435D0B712218Aa8BB1609
Contract address 2 : 0x0D3ACA076712DE598DF856cEcEF76daD38F0A75b
New Contract address: 0xf9d92BAd7b1410dfFB0a204B7aa418C9fd5A898F

And we created a new dex on Ethereum Mainnet
The newly deployed contract information on polygon is shown below.

factory: '0x2D723f60ad8da76286B2aC120498A5EA6bAbC792'
router02: '0x72A0B5Ca437e2f161Ae02C7013d8dD61d5401749'
WETH: '0xE0B469cb3EDA0ecE9E425CFeDa4DF986a55eA9f8'
NPT(Multichain NPT): '0x306ee01a6bA3b4a8e993fA2C1ADC7ea24462000c'
ETH-NPT : '0x89298D7B45C99a54D67d065682eF30D990732634'
USDT-NPT: '0xb0Df2D24e04717aC96f96107d63ECB5549A52F33'
EL-NPT:   '0x3758D1baB8e9eCD4084fDFe7810aA513Bd2733C9'
HVH-NPT:  '0x2A00f85cb4aD84452d923877EDc1eb6Dc43394aA

**Comment by g1nt0ki** [comment]
hi @yepp4you I have fixed it:

https://github.com/DefiLlama/DefiLlama-Adapters/commit/f4efa6184348da9ea931c0c8b309ca65d1e2ad3e

https://github.com/DefiLlama/DefiLlama-Adapters/commit/7571ec967a8688cf042d251b9db78a4d2136dba1
