### ISSUE TITLE
zksync Cannot read properties of undefined (reading 'call')

### ISSUE THREAD

**Issue by mrppk** [DefiLlama/DefiLlama-Adapters#6246]
TypeError: Cannot read properties of undefined (reading 'call')
Truncated error stack:
    at C:\Users\chenkaihong\Desktop\study\DefiLlama-Adapters\node_modules\@defillama\sdk\build\abi\index.js:154:82
    at new Promise (<anonymous>)

**Comment by g1nt0ki** [comment]
if issue persists, please open new issue with more info
