### ISSUE TITLE
Category Mismatch between what is shown in the frontend and what was stated in the PR

### ISSUE THREAD

**Issue by ceilican** [DefiLlama/DefiLlama-Adapters#6249]
This PR (https://github.com/DefiLlama/DefiLlama-Adapters/pull/6212) was recently merged and it appeared in the frontend here (https://defillama.com/protocol/djed-alliance). However, the frontend is wrongly classifying this project in the "CDP" category, even though the PR stated that the category should be "algo-stables". How can this be fixed?

**Comment by g1nt0ki** [comment]
hi @ceilican but it is a CDP right?

**Comment by ceilican** [comment]
Hi @g1nt0ki .  How do you define  "CDP" and how do you define "algo-stables"?

Djed is:
*  "crypto-backed", in the sense that every stablecoin is backed by at least 1 USD worth of the reserve crypto asset (i.e. mADA))
* "algorithmic", in the sense that the contract follows well-defined rules (i.e. an "algorithm") to decide how to mint and burn stablecoins and reservecoins as requested by users. 

Djed is not "CDP", because stablecoins are not issued as a loan associated with a collateralized debt position (as, for instance, DAI is).

Djed is not "unbacked", which is sometimes referred to as "purely algorithmic" (as, for instance, Ampleforth is).

**Comment by ceilican** [comment]
There is a difference between "backing" and "collateralization".  But could it be that DefiLlama is grouping them all together in the "CDP" category?
