### ISSUE TITLE
Add a Stable Swap AMM on pulsechain

### ISSUE THREAD

**Issue by grassprotocol** [DefiLlama/DefiLlama-Adapters#6325]
Component Swap is an AMM for assets of the same numeraire

It's a fork of shell protocol v1.

Website : https://componentswap.xyz/

Active pool: 50% USDC 25% DAI 25% USDT tripool
Contract: https://scan.pulsechain.com/address/0x35C49cB4fa16C557968cF43e237674b38bf05327

**Comment by g1nt0ki** [comment]
it is added
