### ISSUE TITLE
Solana Support for Transactions/Gas Used 24h

### ISSUE THREAD

**Issue by 0xbigz** [DefiLlama/DefiLlama-Adapters#6356]
see these stats for some evm protocols. browsing /projects folder couldnt figure out how it was calculated

would love some pointers how its calc and willing to help write this

```
Transactions 24h
Gas Used 24h
```

**Comment by 0xngmi** [comment]
It's using the code from here: https://github.com/DefiLlama/dimension-adapters/tree/master/users

We just look up all the txs against a list of addresses associated with each protocol, if you could add protocol addresses for solana I'll make the infra changes to support these so we can display those metrics for solana protocols as well
