### ISSUE TITLE
How to fix the graph due to the migration?

### ISSUE THREAD

**Issue by curbisn** [DefiLlama/DefiLlama-Adapters#6466]
We did the migration manually 2 days ago and completed the updated adapter with the new smart contracts yesterday.

Is it possible to fill up the volume gap that we withdrew all funds at that time? Now that funds are secured by the new smart contracts.

![Screenshot 2023-06-03 at 12 39 57](https://github.com/DefiLlama/DefiLlama-Adapters/assets/130688524/4373c5a2-18f6-4581-88ab-0d17a935efc1)

URL: https://defillama.com/protocol/dexilla

Thank you.

**Comment by realdealshaman** [comment]
@curbisn Hey, sure thing. I've filled the volume gap now 👍
