### ISSUE TITLE
[NEOPIN] adding New Ether Liquid Staking Protocol to Ethereum  

### ISSUE THREAD

**Issue by yepp4you** [DefiLlama/DefiLlama-Adapters#6580]
@g1nt0ki  

The protocol  is not yet live, but the ETH that will be used initially has already been deposited and is waiting to be registered as a validator. 
The npEth erc20 token is similar to lido's wstEth.

npEth 
  - address : 0x841d3B6660663Ed4B0D9b9EDAEe6642e05A4E182
  - function :   function getTotalPooledEth() public view returns (uint256)
  
Thanks

**Comment by Define101** [comment]
Would be great if you guys could make an adapter . One example here https://github.com/DefiLlama/DefiLlama-Adapters/blob/main/projects/stakehound/index.js

We will need to make another listing

**Comment by yepp4you** [comment]
@Define101 

In the code below, which is an existing neopin project, can i plus the liquid staking TVL in addition to the Klaytn and Ethereum parts?

const { uniTvlExport } = require('../helper/unknownTokens')
const { mergeExports } = require('../helper/utils')

module.exports = mergeExports([
  uniTvlExport('klaytn', '0x1a1F14ec33BF8c2e66731f46D0A706e8025b43e9'),
  uniTvlExport('polygon', '0x1289ae78422b94414c1F827C534a1fE8E31E71Aa'),
  uniTvlExport('ethereum', '0x2D723f60ad8da76286B2aC120498A5EA6bAbC792'),
]

**Comment by yepp4you** [comment]
@g1nt0ki 
I requested a pull request. 
thanks

https://github.com/DefiLlama/DefiLlama-Adapters/pull/6614
