### ISSUE TITLE
How to display LSD/ETH Peg and Mcap/TVL in the Total Value Locked ETH LSDs page?

### ISSUE THREAD

**Issue by bill-clippy** [DefiLlama/DefiLlama-Adapters#6594]
Tranchess has recently submitted PRs to create a ***Tranchess Ether*** project tracking the ETH LSD of our ETH Fund with staking strategy. We would like to further associate the project with Tranchess' qETH token. What are the steps to take to properly display LSD/ETH Peg and Mcap/TVL in the [Total Value Locked ETH LSDs](https://defillama.com/lsd) page?

**Comment by Define101** [comment]
Thanks for letting us know
We will get back to you once its live

**Comment by bill-clippy** [comment]
@Define101 Hi, a friendly ping on this, looks like we are still missing qETH token as our LSD. Could you please help? Thanks!
