### ISSUE TITLE
How to change the tooltip in the LSD column ?

### ISSUE THREAD

**Issue by killbond007** [DefiLlama/DefiLlama-Adapters#6602]
Hello,
 On this page (https://defillama.com/lsd), we hope change the message tooltip in the LSD column , How should we set it up?

we want change to Value Accruing Token
<img width="292" alt="Screenshot 2023-06-20 at 16 47 14" src="https://github.com/DefiLlama/DefiLlama-Adapters/assets/22051991/20ec8d8c-601e-49a1-93e6-da053e8ff5a5">

**Comment by g1nt0ki** [comment]
hi @killbond007 no sure if other llamas will agree with the change, but can you create this issue in UI repo and discuss there? https://github.com/DefiLlama/defillama-app
