### ISSUE TITLE
The new VELO Token is not included in the TVL calculation.

### ISSUE THREAD

**Issue by momoex** [DefiLlama/DefiLlama-Adapters#6681]
The new VELO Token address:  ```0x9560e827af36c94d2ac33a39bce1fe78631088db```
The old one:  ```0x3c8B650257cFb5f272f799F5e2b4e65093a11a05```

```node test projects/extra/index.js ```

--- tvl ---
**VELO                      5.58 k**

Seems it's the old VELO.
However, there is about 300k new VELO.

Could you help check this?

**Comment by g1nt0ki** [comment]
hi @momoex sorry for late reply, seems like new VELO token is included now, it has 1.77M tvl
