### ISSUE TITLE
sumTokensExport should have an option param to ignore certain token holder addressess

### ISSUE THREAD

**Issue by eserilev** [DefiLlama/DefiLlama-Adapters#6763]
In order to track TVL, bridge projects include the token addresses that should be counted as part of their TVL. However sometimes, certain portions of that token are "out of circulation". They are held in wallets that are marked by coingecko/coinmarketcap etc. as "out of circulation" wallets. There should be an easy way to include those wallet addresses in `sumTokensExport` so that the correct TVL values can be calculated for tokens in this category.

**Comment by g1nt0ki** [comment]
Not sure if your example is applicable for sumTokens, one needs to explicitly pass list of owners to count tvl. for bridges, we count the tvl in the source chain, if they have minted more and held it on particular wallet to distribute in the future,  it makes no difference as we count tvl at source

**Comment by eserilev** [comment]
@g1nt0ki 

> if they have minted more and held it on particular wallet to distribute in the future, it makes no difference as we count tvl at source

this is currently not 100% true. I work for chainport and defillama refuses to count TVL for the copi token. 

the project Cornucopias transferred their total token supply from ETH to BNB using our bridge. However a significant portion of the tokens on BNB are not in circulation. According to the discussions in PR #6716 you guys wont count any of our TVL

comment from @llamatester below

> The change you are suggesting would count 114.20 M in TVL coming from copi (which would be ~90% of your TVL), however COPI's marketcap is only 23M according to https://www.coingecko.com/en/coins/cornucopias, so what you'd be counting as TVL would be the whole supply of COPI, including all coins that are locked. This goes against one of the core rules of our methodology, which you can find on https://docs.llama.fi/list-your-project/readme:

> We don't count any tokens that are not circulating or are yet to be issued

> We also apply the same methodology to cross-chain tokens on multichain, where when the whole supply is bridged we cap what is counted as TVL, and for axelar, another bridge protocol, we don't count AXL, which is also a cross-chain token and would make up the majority of their TVL, so the same methodology is applied to all protocols on defillama. If you spot a protocol where we're not applying this methodology please let us know and we'll fix it.

**Comment by eserilev** [comment]
@g1nt0ki this issue is not resolved, i'm not sure why you closed it

**Comment by eserilev** [comment]
ah ok, I didnt realize you added that functionality. thank you @g1nt0ki
