### ISSUE TITLE
Add rockswap on Pulsechain

### ISSUE THREAD

**Issue by grassprotocol** [DefiLlama/DefiLlama-Adapters#6829]
A unique layered system with delegated farming and deflationary tokenomics on pulsechain.

Twitter: https://twitter.com/RockSwapFi

Rock token: 0x8DF097C665e84C9ee6A657B055e460BfC82407e0
Masterchef: 0x09c7506C185947B2C2764A85A942CFbC6F07CcF4

**Comment by g1nt0ki** [comment]
twitter handle gone and site is down: https://rockswap.finance/
