### ISSUE TITLE
CoinDrip adapter issue

### ISSUE THREAD

**Issue by razvanstatescu** [DefiLlama/DefiLlama-Adapters#6853]
Hi @g1nt0ki, I've seen you modified our CoinDrip adapter in [this commit](https://github.com/DefiLlama/DefiLlama-Adapters/commit/e0e683cfac791424a8c9da53628132e471b4065e) to track OneDex and added all tokens locked in the protocol (except WEGLD) under vesting. Not sure if that is what you intended to do, as not all tokens that are streamed through CoinDrip are necessary to do vesting through us.

Thanks!

**Comment by g1nt0ki** [comment]
hi @razvanstatescu when the project for first listed I naively thought the steaming is going to only stablecoins, I should split it from the start sorry.

As to why I made the commit, for streaming/payment protocols, we consider only chain native tokens/stablecoins as tvl, everything else as vesting. The reason we do this is to have apples-to-apples comparison: try toggling vesting on/off here and you will see the difference: https://defillama.com/protocols/payments Vesting is not the right term, but it is the closest we have.

We apply the same logic for our own product listing: https://defillama.com/protocol/llamapay


Unfortunately, we dont have refill support for GLD yet, do you prefer if we reset the chart and track from now?

**Comment by razvanstatescu** [comment]
Thanks for the answer @g1nt0ki, it clarified the issue for me 🙏. One more thing: right now, I see only EGLD and WEGLD tokens are tracked. I'll make a PR tomorrow to also include stablecoins (or, are they included?)

Thanks!

**Comment by g1nt0ki** [comment]
> Thanks for the answer @g1nt0ki, it clarified the issue for me pray. One more thing: right now, I see only EGLD and WEGLD tokens are tracked. I'll make a PR tomorrow to also include stablecoins (or, are they included?)
> 
> Also, yes, I think is ok to reset thee chart.
> 
> Thanks!

yeah, please do, I think I missed it

**Comment by g1nt0ki** [comment]
fixed the issue
