### ISSUE TITLE
Add Retro coingecko ID

### ISSUE THREAD

**Issue by christianholman** [DefiLlama/DefiLlama-Adapters#7032]
[Retro](https://defillama.com/protocol/retro) has been listed on coingecko with the it "retro-finance". While submitting the adapter I noticed there was a field to include a coingecko id, which didn't exist back then.

defillama id: retro
coingecko-id: retro-finance

https://defillama.com/protocol/retro
https://www.coingecko.com/en/coins/retro-finance

**Comment by Define101** [comment]
Thank you so much for letting us know
We have added now
