### ISSUE TITLE
JewelSwap Leveraged Yield Farming TVL

### ISSUE THREAD

**Issue by combased-dev** [DefiLlama/DefiLlama-Adapters#7077]
Hello, @g1nt0ki there is an issue with the TVL calculation of Leveraged Yield Farming from JewelSwap
At the moment DefiLlama displays 344k TVL, while our website displays 440k. This is because you don't include our token (JWLEGLD) into calculation. It is a token pegged to EGLD, so the price is the same as EGLD. Since we have a farm of EGLd-JWLegld worth of 200k, only 100k is calculated :) let me know if you need any other info, thanks!

**Comment by g1nt0ki** [comment]
hi @combased-dev think this fixes the issue: https://github.com/DefiLlama/DefiLlama-Adapters/pull/7114

Issue was, only half the JWLEGLD LP tokens are in farm contract, other half are here: https://explorer.multiversx.com/accounts/erd1qqqqqqqqqqqqqpgqx6833qjac6uqztgsa8jhlztexucke0hrdfys6wd7qt/tokens but what is this contract?

**Comment by combased-dev** [comment]
@g1nt0ki correct, this is our egld liquid staking, so all good, you can merge, thanks!
