### ISSUE TITLE
Missing data from Liquid Collective

### ISSUE THREAD

**Issue by josh-alluvial** [DefiLlama/DefiLlama-Adapters#7181]
When submitting PR I didn't see a spot to add this information or perhaps I missed.

In the grid view: https://defillama.com/lsd the following information can be added to Liquid Collective:

LSD = LsETH (type = Value Accuring Token or cToken)
Fee = 15%

**Comment by Technocv** [comment]
technocraftic

**Comment by realdealshaman** [comment]
this has now been added
