### ISSUE TITLE
Wrong TVL Data for TProtocol

### ISSUE THREAD

**Issue by tpktpj** [DefiLlama/DefiLlama-Adapters#7269]
Looks like the Defillama website set a wrong TVL data source for TProtocol(https://twitter.com/TProtocol_). Right now, Defillama website treat the USDC balance in TProtocol OTC wallet as TVL, which is wrong. 

Following the Defillama adapter of TProtocol, TVL sould be the STBT value in TProtocol Treasury: https://etherscan.io/token/0x530824DA86689C9C17CdC2871Ff29B058345b44a?a=0xa01D9bc8343016C7DDD39852e49890a8361B2884

**Comment by g1nt0ki** [comment]
hi @tpktpj 

DO you know of some on chain oracle to price STBT tokens? looks like coingecko rugged it hence the drop in tvl: https://www.coingecko.com/en/coins/short-term-t-bill-token
