### ISSUE TITLE
Based Farm DefiLlama page included unrelated projects

### ISSUE THREAD

**Issue by BasedDotFarmDev** [DefiLlama/DefiLlama-Adapters#7371]
https://github.com/DefiLlama/DefiLlama-Adapters/pull/7364

Was https://defillama.com/protocol/based-farm previously used?

It's showing 'Based Finance', 'Based V1', and 'Based Next Generation', but these are completely different projects.

Do we need to migrate Based.Farm to a different link? Thank you.

**Comment by g1nt0ki** [comment]
think it is fixed now? https://defillama.com/protocol/based-farm
