### ISSUE TITLE
TFBX token 0 price problem

### ISSUE THREAD

**Issue by K-NRS** [DefiLlama/DefiLlama-Adapters#7464]
Hi. I am writing for truefeedback project. 
https://defillama.com/protocol/truefeedback

As you can see our TVL seems to be 0 since Augst 5th. I am investigating our TVL problem. I see that coingecko id of trufeedback is added to the file below.
https://github.com/DefiLlama/defillama-server/blob/master/coins/src/adapters/other/distressedAssets.ts

Truefeedback is listed on MEXC exchange and has staking program on Celo and Kava chains. But TVL on this chains are 0 now. Can you fix this problem.

**Comment by realdealshaman** [comment]
@K-NRS Did the staking contracts change? I see that there is a new token address on coingecko

Was there a V2 released?

**Comment by K-NRS** [comment]
@realdealshaman Hi again. Can you guide me on this? What should we do now?

**Comment by realdealshaman** [comment]
@K-NRS hey, thanks for the ping, I've corrected the adapter so that it will now export the staking tvl
