### ISSUE TITLE
JewelSwap update

### ISSUE THREAD

**Issue by combased-dev** [DefiLlama/DefiLlama-Adapters#7469]
Hello, @g1nt0ki ! We have launched a new feature by integrating Hatom lending. You can now deposit tokens and we provide an APY. The problem is that, even if it is our SC, we don't hold the assets ourselves. Thus, can we create a PR where we query from SC our positions - same to what we do in the UI? There is no other way tbh. Here is a link to our [protocol](https://explorer.multiversx.com/accounts/erd1qqqqqqqqqqqqqpgqxdgq3ljejerqew4e22u0u5pr4vejx6p3dfysfwxqww) and some [example transactions](https://explorer.multiversx.com/transactions/0ea0b87fb900109caf4725c695beedbf49829a3c610fa8a6e63b82f8088e021c)

Here is our feature https://app.jewelswap.io/farm/hatom

Also, please add two new Staking SCs (the tokens are on-chain), so it is easier. These two scs:
HTM - [here](https://explorer.multiversx.com/accounts/erd1qqqqqqqqqqqqqpgqrhulnk8ughrghu9vyuy5hatd2nmaewnfvmuswq0wsv) (take into account SHTM (staked hatom)
MEX - [here](https://explorer.multiversx.com/accounts/erd1qqqqqqqqqqqqqpgqa4ws73d57lvsgvm7cn63rx8rt3ks44pqvmus39n5z6/tokens)
(take into account SMEX (staked mex)

**Comment by combased-dev** [comment]
@g1nt0ki any suggestions?

**Comment by g1nt0ki** [comment]
hi @combased-dev sorry, I am working part time now, can you put up a PR with the changes and I can review/merge it, else will be back in two weeks and fix it myself.

Yes, we can query the SC to get your position in hatom to include in your tvl
