### ISSUE TITLE
HopeMoney fix catalog and icon

### ISSUE THREAD

**Issue by XuMinhui** [DefiLlama/DefiLlama-Adapters#7743]
Hi admin, first of all, thanks for the inclusion!

But there are a couple of small issues that I need your help to fix
This is the current catalog
![image](https://github.com/DefiLlama/DefiLlama-Adapters/assets/57860492/48c395c6-0308-4c51-b10f-618228712bcc)
The page display we expect is
![image](https://github.com/DefiLlama/DefiLlama-Adapters/assets/57860492/3ccbe085-2be4-4872-ab8b-292c88c16ba3)
Here is a detailed description of the modifications

1. The first level heading HOPE Money => HopeMoney (note the case and no space), the icon is changed to: https://icons.llamao.fi/icons/protocols/hope-collateral?w=48&h=48
2. the secondary heading "Hope Collateral" is changed to "Hope Staking", the type belongs to "Liquity Satking". The icon for this item should be changed to https://icons.llamao.fi/icons/protocols/hope-collateral?w=48&h=48
3. "HOPE Swap" changed to "Hope Swap" type is "Dexes"
4. "HOPE Lend" changed to "Hope Lend" type is "Lending"

Note: Our team is a group of obsessive-compulsive members and pays close attention to details, we hope you can pay attention to case and icon during the modification process, thank you very much!

**Comment by XuMinhui** [comment]
![image](https://github.com/DefiLlama/DefiLlama-Adapters/assets/57860492/a436891d-b105-4882-9f4d-2a9685e922dd)
Why is there this update?

**Comment by g1nt0ki** [comment]
closing this as old, I think we discussed this on discord?
