### ISSUE TITLE
Reorganize Factor Protocol

### ISSUE THREAD

**Issue by dimasriat** [DefiLlama/DefiLlama-Adapters#7745]
# Abstract
We need to consolidate all tabs under a single one called `factor` (meaning we remove v1, v2, leverage vault). It's one protocol and one token, so a unified page makes the most sense. There should be just one protocol url which is `https://defillama.com/protocol/factor`.

# Motivation
Currently, there are 3 different section in factor pages: `factor-v1`, `factor-v2` and `factor-leverage-vault`. Actually, all of those are not different product among each other. They are actually building blocks and parts of the greater product which is `Factor Studio`.

What is Factor Studio? Factor Studio enables the creation and management of a wide range of DeFi instruments, including vaults, yield pools, lending pools, liquidity pools, tokenized baskets, and custom DeFi primitives. These instruments can be combined and customized to meet specific investment strategies and goals. Some upcoming use cases for Factor Studio include the creation and management of lending pools for different assets and protocols, the support for on-chain derivatives with flexible parameters, and the development of custom DeFi primitives tailored to specific needs. These use cases further expand the possibilities for innovation and collaboration within the DeFi landscape.

# Specification
1. In [Defillama-Adapter](https://github.com/DefiLlama/DefiLlama-Adapters), combine `factor-v1`, `factor-v2`, `factor-leverage-vault` into one protocol folder which is `factor`.
2. In [yield-server](https://github.com/DefiLlama/yield-server), I've already create a [PR here](https://github.com/DefiLlama/yield-server/pull/1041) for tracking APY of factor yield vaults. But I can't set it to `factor` as the project name because there are only `factor-v1`, `factor-v2` and `factor-leverage-vault` in the protocol slug. So I propose to change the protocol slugs for `factor-v1`, `factor-v2` and `factor-leverage-vault` into single protocol slug under the name `factor` and then change the project name on my PR in the yield server from `factor-v2` to `factor`, so it will pass the test.

# Related URL
https://defillama.com/protocol/factor
https://defillama.com/protocol/factor-v1
https://defillama.com/protocol/factor-v2
https://defillama.com/protocol/factor-leverage-vault

**Comment by 0xngmi** [comment]
looks like this is already live: https://defillama.com/protocol/factor

**Comment by dimasriat** [comment]
> looks like this is already live: https://defillama.com/protocol/factor

<img width="615" alt="image" src="https://github.com/DefiLlama/DefiLlama-Adapters/assets/59865105/5eb8bde6-5fad-4c14-a69a-3e24a9161fc3">

Yes, but we don't need something like this (Factor V1, Factor V2, Factor Leverage Vault). It's because we are gonna integrate them like a lego blocks. It's not like `what it called V1` is not used again. When we compare with Uniswap let's say, we are not using V1 and V2 anymore.

**Comment by dimasriat** [comment]
Any updates?

also could you change the `Factor` tab logo to new logo (like in `Factor-V1, `Factor-V2`)
