### ISSUE TITLE
Could you also include staking TVL for BenSwap?

### ISSUE THREAD

**Issue by BenTokenFinance** [DefiLlama/DefiLlama-Adapters#792]
Contract name is MasterBreeder (equivalent to MasterChef).
SmartBCH: 0xDEa721EFe7cBC0fCAb7C8d65c598b21B6373A2b6 (All Contracts: https://docs.benswap.cash/security/contracts)
BSC: 0x03245d87295cd0783E1f10a2EA54F9E80B726aF8  (All Contracts: https://docs.benswap.finance/security/contracts)

Many thanks!!

**Comment by BenTokenFinance** [comment]
And BenSwap is not showing on the SmartBCH page.  Please include. Thank you!

**Comment by BenTokenFinance** [comment]
BTW BenSwap has different tokens on SmartBCH and BSC.
EBEN is for SmartBCH and GBEN is for BSC.
Thank you!

**Comment by BenTokenFinance** [comment]
Great site and appreciate the listing and SmartBCH network support!!   Missing staking TVL like this:
https://vfat.tools/bsc/benswap/
https://vfat.tools/smartbch/benswap/

**Comment by 0xngmi** [comment]
> And BenSwap is not showing on the SmartBCH page. Please include. Thank you!

just applied a fix for this, should appear on the website in a bit

**Comment by 0xngmi** [comment]
Would it be possible to get GBEN/EBEN listed on coingecko? that would help us a lot in getting staking counted for them

**Comment by BenTokenFinance** [comment]
> Would it be possible to get GBEN/EBEN listed on coingecko? that would help us a lot in getting staking counted for them

Thank you sir.  We are working on all kinds of listings.  Right now on SmartBCH we don't have EBEN based pairs staked yet. All staking pairs are BCH based so that is probably easier.  On the BSC side the TVL is low so ignoring GBEN based pair would be also OK.

Anyways, we are working on Coingecko and all other listings and will update with you if any news. Thank you so much sir.

**Comment by BenTokenFinance** [comment]
Well there is a EBEN pool on SmartBCH so I definitely see what you are saying. We will try to list it on Coingecho as soon as we can. I would really appreciate if you could use the LP to get the price as a solution for now. Thanks a lot

**Comment by BenTokenFinance** [comment]
And EBEN is our main focus currently so the BSC tracking isn't so important as SmartBCH

**Comment by BenTokenFinance** [comment]
https://www.smartscan.cash/address/0x0D4372aCc0503Fbcc7EB129e0De3283c348B82c3
This is the EBEN/WBCH LP by the way. Thanks a lot

**Comment by BenTokenFinance** [comment]
In case you also need:

On BSC:
WBNB: https://bscscan.com/token/0xbb4CdB9CBd36B01bD1cBaEBF2De08d9173bc095c
GBEN/WBNB LP: https://bscscan.com/address/0x47Cdc99BC15951fA65D9b0a078d571aFBC332A9a
BUSD Token: https://bscscan.com/token/0xe9e7CEA3DedcA5984780Bafc599bD69ADd087D56

On SmartBCH:
WBCH: https://www.smartscan.cash/address/0x3743eC0673453E5009310C727Ba4eaF7b3a1cc04

**Comment by 0xngmi** [comment]
at the moment we should be tracking all the LP pools (including EBEN ones, if you notice that we are missing one just let us know), but for pure EBEN/GBEN staking (counting EBEN staked on the masterchef) it would be great to have coingecko support

**Comment by BenTokenFinance** [comment]
OK sir I made a pull request to get a more accurate TVL for BenSwap (SmartBCH).  I tested locally. Could you kindly merge?  Thanks a bunch!

https://github.com/DefiLlama/DefiLlama-Adapters/pull/805

**Comment by BenTokenFinance** [comment]
Could you check Telegram DM sir?

**Comment by 0xngmi** [comment]
everything should be updated now, is it good?

**Comment by BenTokenFinance** [comment]
DMed you sir

**Comment by 0xngmi** [comment]
Closing this, the bug you mentioned in telegram has been fixed too
