### ISSUE TITLE
How are cases of token migrations handled?

### ISSUE THREAD

**Issue by encrypted-soul** [DefiLlama/DefiLlama-Adapters#8000]
Currently in [projects/helper/coreAssets.json](https://github.com/DefiLlama/DefiLlama-Adapters/blob/main/projects/helper/coreAssets.json#L10) the address of `MATIC` is stored as `0x7d1afa7b718fb893db30a3abc0cfc608aacfebb0` for ethereum.

However if we visit etherscan for this token address we will notice a token migration announcement - https://etherscan.io/token/0x7d1afa7b718fb893db30a3abc0cfc608aacfebb0.
![image](https://github.com/DefiLlama/DefiLlama-Adapters/assets/62807661/83392567-295b-42f4-8ebf-4e43e3b9e51c)

In general how are the cases of token migrations handled across the chains and protocols. Is it just manual reporting and staying on top of things?

**Comment by encrypted-soul** [comment]
@0xngmi any context here would be helpful

**Comment by g1nt0ki** [comment]
hi @encrypted-soul unfortunately yeah, it is a manual process. but at this point, we dont have to do anything for matic migration right? old token is still used in places and supported right?

if that is the case, I would create new entry for POL in coreAssets.json file

**Comment by Radiwit** [comment]
I can left You your own deposit on start + 3 b thats enough invest

**Comment by Radiwit** [comment]
Can some1 help me with withdraw some crypto
