### ISSUE TITLE
defilamva vivaleva TVL tracking has not been available

### ISSUE THREAD

**Issue by geunwoobaek** [DefiLlama/DefiLlama-Adapters#8054]
# issue
vivaleva TVL tracking has not been available since November 4th. But I haven't modified the code. Thank you for checking.

# error message
```
➜  DefiLlama-Adapters git:(main) ✗ node test.js projects/vivaleva/index.js 
sdk.api.abi.call errored with params: [
  {
    chain: 'era',
    block: undefined,
    target: '0xF9cda624FBC7e059355ce98a31693d299FACd963',
    abi: 'function tryAggregate(bool requireSuccess, tuple(address target, bytes callData)[] calls) payable returns (tuple(bool success, bytes returnData)[] returnData)',
    params: [ false, [Array] ],
    skipCache: true
  }
]
sdk.api.abi.call errored with params: [
  {
    chain: 'era',
    block: undefined,
    target: '0xF9cda624FBC7e059355ce98a31693d299FACd963',
    abi: 'function tryAggregate(bool requireSuccess, tuple(address target, bytes callData)[] calls) payable returns (tuple(bool success, bytes returnData)[] returnData)',
    params: [ false, [Array] ],
    skipCache: true
  }
]

 ------ ERROR ------ 


PromisePoolError: call revert exception [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method="tryAggregate(bool,(address,bytes)[])", data="0x", errorArgs=null, errorName=null, errorSignature=null, reason=null, code=CALL_EXCEPTION, version=abi/5.7.0)
Truncated error stack:
    at PromisePoolError.createFrom (/Users/richard/workspace/DefiLlama-Adapters/node_modules/@supercharge/promise-pool/dist/promise-pool-error.js:28:16)
    at async Promise.all (index 0)
```
    
 <img width="1252" alt="image" src="https://github.com/DefiLlama/DefiLlama-Adapters/assets/39114544/e6009945-9d69-453c-b54c-ba9e377e186f">
 
# defillama image
<img width="1465" alt="image" src="https://github.com/DefiLlama/DefiLlama-Adapters/assets/39114544/56df4021-0200-48b4-8397-91e639146299">

https://defillama.com/protocol/vivaleva-protocol

**Comment by geunwoobaek** [comment]
[g1nt0ki](https://github.com/g1nt0ki) could you check about this issue? 🙇

**Comment by geunwoobaek** [comment]
[g1nt0ki](https://github.com/g1nt0ki)
https://github.com/DefiLlama/DefiLlama-Adapters/pull/7846 this PR works! 
<img width="605" alt="image" src="https://github.com/DefiLlama/DefiLlama-Adapters/assets/39114544/cb440866-365a-4367-85b7-756942428577">

but this PR https://github.com/DefiLlama/DefiLlama-Adapters/pull/7864 not works!

**Comment by g1nt0ki** [comment]
closing this as fixed here: https://github.com/DefiLlama/DefiLlama-Adapters/commit/7047e5a9b9d5eff8a572c1c1fa6ce4bd3070c7b4
