### ISSUE TITLE
Update logo for Chimeradex

### ISSUE THREAD

**Issue by chimeradex** [DefiLlama/DefiLlama-Adapters#8098]
Hi admin, I'm from Chimeradex Team,Our project was listed on Defilama not long ago,but I want to update it with a new logo.
Can you please update this on your website?
Thank your team in advance !
Links to our projects on Defilama:
https://defillama.com/protocol/chimeradex

List new logo links:
https://github.com/chimeradex/Logo/blob/main/png/token_1024x1024.png

**Comment by Define101** [comment]
Its done

**Comment by Define101** [comment]
https://icons.llamao.fi/icons/protocols/chimeradex?w=48&h=48
