### ISSUE TITLE
Not listed in derivatives

### ISSUE THREAD

**Issue by eugenelhj** [DefiLlama/DefiLlama-Adapters#8245]
Hi, how can we get Demex from Carbon chain to be listed in https://defillama.com/derivatives ?

**Comment by Define101** [comment]
We have changed the category to derivatives

**Comment by eugenelhj** [comment]
> We have changed the category to derivatives

HI, can kindly help to check again as I still do not see it in derivatives :/

**Comment by eugenelhj** [comment]
> We have changed the category to derivatives

thanks for the help! I see that Demex category is now derivatives but we are still not listed under https://defillama.com/derivatives , pls advice thanks!
@Define101 @g1nt0ki

**Comment by Define101** [comment]
> > We have changed the category to derivatives
> 
> thanks for the help! I see that Demex category is now derivatives but we are still not listed under https://defillama.com/derivatives , pls advice thanks! @Define101 @g1nt0ki

Thats a different code/repo
We need a PR here https://github.com/DefiLlama/dimension-adapters/tree/master/dexs
