### ISSUE TITLE
Update DigiFT  Protocol Information

### ISSUE THREAD

**Issue by whucsfzf** [DefiLlama/DefiLlama-Adapters#8353]
Hi,
Here's the page:  https://defillama.com/protocol/digift

New Protocol Information:

DigiFT is the first regulated exchange for on-chain real-world assets, approved as a Recognised Market Operator with a Capital Markets Services license by the Monetary Authority of Singapore. DigiFT allows asset owners to issue blockchain-based security tokens and investors can trade with continuous liquidity via an AMM.

**Comment by whucsfzf** [comment]
@Define101  Can you help to update DefiLlama's website ？Thanks

**Comment by Define101** [comment]
Hi, thanks for letting us know
Should be live within 1 hour

**Comment by whucsfzf** [comment]
Thanks.
