### ISSUE TITLE
Add Gryphon

### ISSUE THREAD

**Issue by winston3366** [DefiLlama/DefiLlama-Adapters#8364]
Name (to be shown on DefiLlama):
Gryphon

Twitter Link:
https://twitter.com/Gryphon_fi

List of audit links if any:

Website Link:
https://gryphon.finance/

Logo (High resolution, will be shown with rounded borders):
https://app.gryphon.finance/Logo.png

Current TVL:
380.44k

Treasury Addresses (if the protocol has treasury)

Chain:
Injective

Coingecko ID (so your TVL can appear on Coingecko, leave empty if not listed): (https://api.coingecko.com/api/v3/coins/list)
Coinmarketcap ID (so your TVL can appear on Coinmarketcap, leave empty if not listed): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)

Short Description (to be shown on DefiLlama):
Injective’s premier liquid staking platform.With an integrated money market to earn compounded interest on Injective while accessing your locked liquidity.

Token address and ticker if any:
Category (full list at https://defillama.com/categories) *Please choose only one:
LSD

Oracle used (Chainlink/Band/API3/TWAP or any other that you are using):
PythOralce

forkedFrom (Does your project originate from another project):
https://github.com/DefiLlama/DefiLlama-Adapters

methodology (what is being counted as tvl, how is tvl being calculated):
Count the sum of the two tokens (INJ, ATOM) of the dapp platform.

Github org/user (Optional, if your code is open source, we can track activity):
https://github.com/GryphonProtocolDAO

**Comment by g1nt0ki** [comment]
It is listed now: https://defillama.com/protocol/gryphon
