### ISSUE TITLE
ParaX rebranding to Parallel

### ISSUE THREAD

**Issue by jfzhou5** [DefiLlama/DefiLlama-Adapters#8415]
Our team is planning to rebrand the ParaX to Parallel. We need to update the following contents:

1. Update the name of the parent protocol from "ParaX Super App" to "Parallel Super App". 
2. Update the logo of "Parallel Super App" with [https://parallel.fi/favicon.ico](https://parallel.fi/favicon.ico).
3. Update the Protocol information of Parallel Super App.
    1. --**New Protocol Information**--: The Parallel Super App, deployed on the universal Layer 2 solution, Parallel, stands as an integrated platform merging Parallel Finance and ParaX products into a user-centric space. Offering a comprehensive range of DeFi functionalities spanning yield generation, lending, staking, trading, and more across diverse blockchain networks, the app confronts existing DeFi challenges. Leveraging Parallel's versatile Layer 2 infrastructure, it delivers benefits like gasless transactions, rapid processing, heightened security, and a seamless DeFi encounter. As an all-in-one solution, the app enables cross-margin NFT lending, staking, trading, and user-friendly features within its interface.
    2. --**Website**--: https://parallel.fi/
4. Rename the Child protocol "Parallel Lending" to "Parallel Polkadot Lending".
5. Rename the Child protocol "Paraspace Lending V2" to "Parallel Lending", And update its protocol information.
    1. --**Protocol information**--: Parallel Lending is a decentralized lending protocol enabling users to borrow and lend using both Non-Fungible Tokens (NFTs) and Fungible Tokens (FTs). It offers the ability to leverage untapped capital for additional investments while generating yields. Notably, Parallel stands out as the pioneer in cross-margin NFT Finance, allowing users to borrow and lend ERC-721 and ERC-20 tokens within a unified account and credit line. This protocol empowers asset holders to access liquidity and earn yields effortlessly across their entire asset portfolio, offering a user-friendly yet robust solution.
    4. --**Webiste**--: https://app.parallel.fi/ethereum/apps/paraspace
    5. --**Audits**--: https://docs.parallel.fi/parallel-finance/security
    6. --**Twitter**--: https://twitter.com/ParallelFi
6. Rename the Child protocol "ParaSpace ApeStaking V2" to "Parallel Staking", And update its protocol information.
    1. --**Protocol information**--: Parallel Staking introduces an innovative approach for users to optimize their ApeCoin staking. By enabling simultaneous staking and borrowing against NFTs like Bored Ape Yacht Club, Mutant Ape Yacht Club, and Bored Ape Kennel Club, it addresses the challenge faced by holders lacking sufficient ApeCoin or NFTs for maximum yields. Parallel resolves this by allowing NFT staking and borrowing ApeCoin against them, facilitating auto-compounding of rewards, and offering Peer-to-Peer staking options. Through this, both NFT and ApeCoin holders can secure fixed shares of auto-compounded rewards, enhancing their staking experience and returns.
    3. --**Webiste**--: https://app.parallel.fi/ethereum/apps/paraspace/ape-staking
    4. --**Audits**--: https://docs.parallel.fi/parallel-finance/security
    5. --**Twitter**--: https://twitter.com/ParallelFi
7. remove the Child protocol "ParaSpace APE Staking V1".
8. Rename the Child protocol "Parallel Liquid Crowdloan" to "Parallel Polkadot Crowdloan".
9. Rename the Child protocol "Parallel AMM" to "Parallel Polkadot AMM".
10. Rename the Child protocol "Parallel Liquid Staking" to "Parallel Polkadot Liquid Staking". 
11. Rename the Child protocol "Parallel DAOfi" to "Parallel Polkadot DAOfi". 
12. Adjust the order of these Child protocols as the following.
    1. Parallel Super App
    2. Parallel Lending
    3. Parallel Staking
    4. Parallel Polkadot Crowdloan
    5. Parallel Polkadot Lending
    6. Parallel Polkadot AMM
    7. Parallel Polkadot Liquid Staking
    8. Parallel Polkadot DAOfi

**Comment by jfzhou5** [comment]
@g1nt0ki Hello guys, So sorry to tag you, We need to make the above updates for the “ParaX Super App”. Could you help to check this?

**Comment by realdealshaman** [comment]
@jfzhou5 I've made the changes, but we cannot update the order of the child protocols. These are ordered based on when they were listed. I also have not removed ParaSpace APE Staking V1, I will have to talk it over with our team since we prefer to keep all products together

**Comment by realdealshaman** [comment]
What is the reason to remove ParaSpace APE Staking V1?

**Comment by jfzhou5** [comment]
That's ok if you can't change the order of these protocols.

**Comment by jfzhou5** [comment]
> What is the reason to remove ParaSpace APE Staking V1?
Actually, we want to merge the Ape staking v1 and v2 as Parallel Staking. Is this change ok?

**Comment by realdealshaman** [comment]
@jfzhou5 we can update the icon and description but we apply the same methodology as to other protocols and so we decided to keep both version separate
