### ISSUE TITLE
Genius Yield: Add value locked in DEX Orders to the TVL Dashboard

### ISSUE THREAD

**Issue by 4TT1L4** [DefiLlama/DefiLlama-Adapters#8429]
The [Genius Yield DEX](https://www.geniusyield.co/) has recently went live on the Cardano Mainnet, but the [Genius Yield DeFi Llama adapter](https://github.com/DefiLlama/DefiLlama-Adapters/blob/main/projects/genius-yield/index.js) is not updated yet.

The [DeFi Llama dashboard of Genius Yield](https://defillama.com/protocol/genius-yield) is only showing the value locked in staking, but the value locked in the orders of this order book based DEX is not yet shown.

The total value locked into DEX orders can be calculated by calculating the balance at the script's payment credential: `edfff663d37fc5f9753bc4222e0da2bfe08aa48db0837d2c329adeb3`

The balance there is a sum of three terms:
- Offered tokens
- Already received, but not yet delivered, payments (from partial fills)
- Fees

**Comment by g1nt0ki** [comment]
hi @4TT1L4 can you share the script address, dunno how to get the balance from the credential

**Comment by 4TT1L4** [comment]
I have created a PR with an initial implementation:
 - https://github.com/DefiLlama/DefiLlama-Adapters/pull/8445

@g1nt0ki 

> dunno how to get the balance from the credential

As far as I know the payment credential based requests are also supported by the blockfrost address endpoint. I might be wrong though. This needs to be checked.

The addresses/{address} endpoint should work with payment credential as well:
 -  https://docs.blockfrost.io/#tag/Cardano-Addresses/paths/~1addresses~1%7Baddress%7D~1total/get

**Comment by 4TT1L4** [comment]
OK. After some further troubleshooting I found the issue.

The Blockfrost API expects a bech32 address, as it is clearly stated in the documentation. The payment crendetials must be also converted into a bech32 address, so it would be accepted.

After doing this; the adapter started to work as expected and the TVL is calculated:

![image](https://github.com/DefiLlama/DefiLlama-Adapters/assets/2914096/79b45998-012f-4b56-a20c-8e6bf5981d3f)

**Comment by g1nt0ki** [comment]
closing as resolved
