### ISSUE TITLE
EOS RAM category as "Dexes"

### ISSUE THREAD

**Issue by DenisCarriere** [DefiLlama/DefiLlama-Adapters#8523]
@g1nt0ki noticed EOS RAM is categorized as "liquid staking" and counted as "Double Count"

Ref: https://github.com/DefiLlama/DefiLlama-Adapters/pull/8505#issuecomment-1871368332

This isn't accurate, EOS RAM is the native system DEX to trade RAM/EOS on the EOS Network.

This should be considered: "Dexes"

<img width="519" alt="image" src="https://github.com/DefiLlama/DefiLlama-Adapters/assets/550895/a4240e43-5c71-416e-b74f-1648032c61ea">

Total "real" assets are tracked https://bloks.io/account/eosio.ram

<img width="773" alt="image" src="https://github.com/DefiLlama/DefiLlama-Adapters/assets/550895/e27287c4-6a3c-4f9a-b981-c21cfe243e7d">

## RAM Sell order

https://bloks.io/transaction/8e1a2fde7ee63737bcb275af57bdaf0b53dc8cbe58c2ad56b5bb936d5f637247?tab=traces

<img width="715" alt="image" src="https://github.com/DefiLlama/DefiLlama-Adapters/assets/550895/7a5fddf6-d162-44b5-94b0-55dcb1097d60">

## RAM Buy order

https://bloks.io/transaction/84eb61f0056fc8cf40388da41abb678c3fb58a95f5b3b6b859d11f54e3fcd32f?tab=traces

<img width="765" alt="image" src="https://github.com/DefiLlama/DefiLlama-Adapters/assets/550895/0ba2deae-337f-48f8-ba93-c36e8e26432b">

However, there's a new product launched by Defibox called bRAM, which is "RAM wrapper"

This one could be considered "double count" since it wraps the native System RAM

https://defibox.io/ram/

These are two different protocols

**Comment by 0xngmi** [comment]
This was re-classified as Dexes a long time ago
