### ISSUE TITLE
Question about adding more info to existed project

### ISSUE THREAD

**Issue by jibswaps** [DefiLlama/DefiLlama-Adapters#8557]
Hi, I'm a dapp developer that working on project called [Jibswap](https://jibswap.com/). (Uniswap v2 forked) on [JBC](https://exp-l1.jibchain.net/)

Is it possible to add more columns e.g. "Fee and Revenue" and "Volume" to [the project](https://defillama.com/protocol/jibswap) using our Uniswap V2 [subgraph](https://graph.jibswap.com/subgraphs/name/jibswap/graphql) and [OpenAPI](https://api.jibswap.com/docs#/Tickers/get_GetTickers)?

It will be great if we can utilize these APIs to DefiLlama.

Info page: https://info.jibswap.com/

**Comment by Define101** [comment]
You can find more informaiton about the fees and volume hee https://github.com/DefiLlama/dimension-adapters
https://docs.llama.fi/list-your-project/other-dashboards

**Comment by jibswaps** [comment]
@Define101 I've submitted the [PR](https://github.com/DefiLlama/dimension-adapters/pull/1106) already.
You may close this issue.
Thank you for your help!
