### ISSUE TITLE
Update new logo for Hexaswap

### ISSUE THREAD

**Issue by ghost** [DefiLlama/DefiLlama-Adapters#8693]
Hi defillama team, Our project was listed on DefiLlama not long ago, but I want to update it with a new logo.

Can you please update this on your website?
Thank your team in advance!

Link to our protocol on Defilama:
https://defillama.com/protocol/hexaswap

New logo link: 
https://raw.githubusercontent.com/hexaswaptlos/tokenlist/main/token/HEXA.png

**Comment by Define101** [comment]
What is the logo?
