### ISSUE TITLE
Warp-dex incorrect liquidity 

### ISSUE THREAD

**Issue by bro-n-bro-0** [DefiLlama/DefiLlama-Adapters#8812]
Hello! Recently, there was a significant drop in liquidity on the warp-dex. I ran a test script in the adapter and noticed that the BOOT token is not included in the final liquidity. How can this be fixed?

```bash
--- bostrom ---
ATOM                      110.93 k
OSMO                      73.58 k
GRAV                      48.222495640191845
JUNO                      15.076973173290002
Total: 184.57 k

--- tvl ---
ATOM                      110.93 k
OSMO                      73.58 k
GRAV                      48
JUNO                      15
Total: 184.57 k

------ TVL ------
bostrom                   184.57 k

total                    184.57 k
```

**Comment by bro-n-bro-0** [comment]
I submitted a pull request with the updated information here, but I'm not sure if it will help.

https://github.com/DefiLlama/defillama-server/pull/5738

**Comment by realdealshaman** [comment]
it was merged, thanks for  the PR

**Comment by bro-n-bro-0** [comment]
@realdealshaman Thanks, but the TVL is still lower than it should be 😰

<img width="383" alt="image" src="https://github.com/DefiLlama/DefiLlama-Adapters/assets/89854952/965115dc-203d-42ba-988f-4aa81c09e755">

**Comment by bro-n-bro-0** [comment]
Oh, now it's fine :) 
Thanks @realdealshaman
