### ISSUE TITLE
[MORPHO BLUE] Bug in the display of Morpho Blue TVL

### ISSUE THREAD

**Issue by tomrpl** [DefiLlama/DefiLlama-Adapters#8899]
<img width="1488" alt="image" src="https://github.com/DefiLlama/DefiLlama-Adapters/assets/75627352/a6082d3d-2e0a-4a95-8204-85301b6fbc7d">

Hello, any can help us identify why there is a bug in the display of the tvl of Morpho Blue?

**Comment by tomrpl** [comment]
Note that I have this when I run:

```node test.js projects/morpho-blue/index.js```

 on my side the main branch of the DL Adapter repo:
<img width="898" alt="image" src="https://github.com/DefiLlama/DefiLlama-Adapters/assets/75627352/f62afafd-9804-4e19-8a88-e0f165abe508">

**Comment by Define101** [comment]
All good now 
![image](https://github.com/DefiLlama/DefiLlama-Adapters/assets/93603962/07aa19ac-1a9d-40b7-b845-6962bd391286)
