### ISSUE TITLE
"Error: Cannot find module '@stacks/transactions'"

### ISSUE THREAD

**Issue by rodrigoeduardo** [DefiLlama/DefiLlama-Adapters#8976]
## Problem

Trying to do `require("../helper/chain/stacks-api")` on an adapter, gives the following error when trying to test that adapter:

![image](https://github.com/DefiLlama/DefiLlama-Adapters/assets/47866438/32e6f339-1ef3-4174-9b87-a1d0e6d72491)

You can see that error on this job: https://github.com/DefiLlama/DefiLlama-Adapters/actions/runs/7922427203/job/21629989139?pr=8975

## Additional information

On `projects/helper/chain/stacks-api.js` file, this missing library is imported on the first line: `const stacks = require('@stacks/transactions')`.

## Probable solution

Adding `@stacks/transactions` library to `package.json` and `package-lock.json` should fix the problem.

**Comment by g1nt0ki** [comment]
closing as fixed: https://github.com/DefiLlama/DefiLlama-Adapters/pull/8977
