### ISSUE TITLE
update Alcor twitter account

### ISSUE THREAD

**Issue by avral** [DefiLlama/DefiLlama-Adapters#8988]
Our twitter account is https://twitter.com/alcorexchange

But here we see the different one: https://defillama.com/protocol/alcor-exchange

There was correct twitter when we applied for the adding our project: https://github.com/DefiLlama/DefiLlama-Adapters/pull/1802

Please fix it, thank you!

**Comment by realdealshaman** [comment]
Hi, thanks for reaching out and pointing this out! We've updated this now
