### ISSUE TITLE
Reset `factor-leverage-vault` TVL chart because of previous bugs

### ISSUE THREAD

**Issue by dimasriat** [DefiLlama/DefiLlama-Adapters#9135]
The previous implementation of defillama adapter for `factor-leverage-vault` [(link here)](https://defillama.com/protocol/factor-leverage-vault) had a bug that already being solved here (#9095) but the TVL still containing the calculation of previous wrong TVL.

![image](https://github.com/DefiLlama/DefiLlama-Adapters/assets/59865105/e2fa3e55-cad6-4c37-9f25-c9855467eb67)
The chart and data in the DB need to be reset and recalculate from the begining using the current adapter

protocol: `factor-leverage-vault`

**Comment by g1nt0ki** [comment]
closing it as it is fixed now: https://defillama.com/protocol/factor-leverage-vault
