### ISSUE TITLE
Request to track TVL for Unverified Third-Party Contracts

### ISSUE THREAD

**Issue by Hendobox** [DefiLlama/DefiLlama-Adapters#9302]
Hello,

I'm the responsible engineer for [Savvy's DeFi Llama adapter](https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/projects/savvy). Our TVL is incorrect. I am trying to resolve it but have hit a few issues.

Our addresses
[0] are holding tokens including gmd-btc-v2, gmd-btc-usdc, yySiloUsdc, etc
[1] but these tokens are not being considered in the `sumTokens2` functions.

We're not sure exactly why. One idea is that these tokens are unverified. Would that be the reason for these tokens not being considered? 

Here is a [WIP PR](https://github.com/savvy-finance/DefiLlama-Adapters/pull/1) with our changes.

[0] List of addresses holding
- 0x7700dab2c9f7d6fb9b85290c4d5a74c4ddc24b9c,
- 0x2fc8e171b2688832b41881aaf3da4d180bda1f33

[1] table of token names and addresses
| token name | address |
| --- | --- |
| gmd-btc-v2 | [0xaa70b24f5b7a2980a91176cf1f223c6e42d5cc88](https://arbiscan.io//address/0xaa70b24f5b7a2980a91176cf1f223c6e42d5cc88) |
| Yield Yak: Silo USDC.e (WBTC) | [0x056e4f4701c7a5bfa95a36154c7135edb134e0c6](https://arbiscan.io//address/0x056e4f4701c7a5bfa95a36154c7135edb134e0c6) |
| Yield Yak: DeltaPrime USDC | [0x5847eb0ac310845510880c6871e0ce6d8b0f57fc](https://arbiscan.io//address/0x5847eb0ac310845510880c6871e0ce6d8b0f57fc) |
| Yield Yak: DeltaPrime WBTC | [0x3b85d87104091fac2940c3d5bda44748c5fea946](https://arbiscan.io//address/0x3b85d87104091fac2940c3d5bda44748c5fea946) |

**Comment by rkhadder** [comment]
@Define101 @g1nt0ki pinging for visibility - happy to further explain as necessary

**Comment by g1nt0ki** [comment]
hi, issue is some of these tokens are not priced, I have added support fo ryield yak tokens here: https://github.com/DefiLlama/defillama-server/commit/0a7f5b51a80c0662f83de26ede85cae7e1fe533f

@waynebruce0x can you add support for the missing gm tokens?

**Comment by rkhadder** [comment]
Thank you @g1nt0ki

**Comment by rkhadder** [comment]
@waynebruce0x @g1nt0ki any update on gm tokens?

**Comment by waynebruce0x** [comment]
We've tried to get in touch with GMD about pricing their tokens but got no reply. Can you help us understand how to calculate the prices of these tokens using contract functions?

**Comment by Hendobox** [comment]
> We've tried to get in touch with GMD about pricing their tokens but got no reply. Can you help us understand how to calculate the prices of these tokens using contract functions?

Our `YieldStrategyManager` contracts have a method `convertSharesToBaseToken` which will take in the yield token and share amount as args and return the equivalent base token and amount. These are the yield strategy contracts that manage BTC and USD related yield/base tokens respectively:

https://arbiscan.io//address/0xdC82E20111767f4a2A76A65BD85E41F7859c7b9f#readProxyContract

https://arbiscan.io//address/0x09Dde6661fd023cf7c3751555347a5cB8687F806#readProxyContract

**Comment by Hendobox** [comment]
Hey @waynebruce0x - The way to get the underlying price for a GMD v2 token is by calling `IGmdVaultV2(vaultAddress).GDpriceToStakedtoken(pid);`

Below is a table of all the v2 pools, their vault addresses, and the pids that map to either side
| pool | vault address | token | pid |  
| --- | --- | --- | --- |
| BTC - USDC | 0xB0F3e3F5C52Ece66Fe44ac7ECedbD06B7aEc11b2 | BTC | 1 |
| BTC - USDC | 0xB0F3e3F5C52Ece66Fe44ac7ECedbD06B7aEc11b2 | USDC | 0 |
| ETH - USDC | 0x5F01D28467953fDa3dc0e2828DAEAbDa0b06CDF3 | ETH | 1 |
| ETH - USDC | 0x5F01D28467953fDa3dc0e2828DAEAbDa0b06CDF3 | USDC | 0 |

**Comment by g1nt0ki** [comment]
@Hendobox thanks for the info, added price support for these tokens now: https://github.com/DefiLlama/defillama-server/commit/a263b58b2957f5480c6a86d8734437eae0d82c18

**Comment by Hendobox** [comment]
Thanks a lot
