### ISSUE TITLE
Request to add ezETH token on Mode Mainnet

### ISSUE THREAD

**Issue by atozICT20** [DefiLlama/DefiLlama-Adapters#9314]
Hi team,
Is it possible to support 'ezETH' token on Mode Mainnet?
Recently, we launched protocol on Mode network, and it uses ezETH token as collateral.
Because of missing ezETH token, the tvl from DefiLlama is not correct.

Please support ezETH token on Mode Mainnet.

Thank you!

**Comment by Define101** [comment]
https://coins.llama.fi/prices/current/mode:0x2416092f143378750bb29b79eD961ab195CcEea5?searchWidth=4h
Closing this issue
