### ISSUE TITLE
update (Segment Finance) new Logo

### ISSUE THREAD

**Issue by sgmntp** [DefiLlama/DefiLlama-Adapters#9436]
Hello Team,

we would like to kindly ask you to update the project's logo for `segment-finance`

<img src="https://github.com/DefiLlama/DefiLlama-Adapters/assets/146187995/f8ef016b-b0bb-4a0f-8f65-a200cff7ae64" width="250" />

_Attached_

- **SVG**: https://github.com/DefiLlama/DefiLlama-Adapters/assets/146187995/f8ef016b-b0bb-4a0f-8f65-a200cff7ae64
- **PNG**: https://github.com/DefiLlama/DefiLlama-Adapters/assets/146187995/1a63fe64-e05c-4898-adbc-beb09e609fb0

---

The original PR #8872 

Thank you in advance, Alex

**Comment by Define101** [comment]
Thanks for letting us know
Should be live within 2 hours
https://github.com/DefiLlama/defillama-server/pull/6329
