### ISSUE TITLE
ctezos website url

### ISSUE THREAD

**Issue by ctezorg** [DefiLlama/DefiLlama-Adapters#9485]
Protocol were listed with the wrong references. Referring to the request pool - https://github.com/DefiLlama/DefiLlama-Adapters/pull/9461
Please change the domain in the website field on the ctez home page. The official mirror domain is https://ctezos.app. Thanks.
https://defillama.com/protocol/ctez

**Comment by 0xngmi** [comment]
https://ctezos.app/ redirects to https://ctez.app/ which is the current listed page

**Comment by ctezorg** [comment]
> https://ctezos.app/ redirects to https://ctez.app/ which is the current listed page (and has been since listed)
Yes, you are right, but on this domain we have a restriction on the countries of use of our products and we need to install a new domain. Do I need to create a PR here? https://github.com/DefiLlama/defillama-server/blob/master/defi/src/protocols/data3.ts
