### ISSUE TITLE
Change protocol website on Defillama

### ISSUE THREAD

**Issue by kaoyaswap** [DefiLlama/DefiLlama-Adapters#9487]
Hello team, We recently applied to list our project, but we changed our website domain zone due to a change of registrar. is it possible to change it on the page? 
Link - https://defillama.com/protocol/kaoyaswap 
Recently PR - https://github.com/DefiLlama/DefiLlama-Adapters/pull/9402
Actual - https://kaoyaswap.xyz

**Comment by Define101** [comment]
Yes. Should be live within 2 hours
We will close this 
https://github.com/DefiLlama/defillama-server/pull/6328
