### ISSUE TITLE
Add Pole Aggregator

### ISSUE THREAD

**Issue by SyblePaul** [DefiLlama/DefiLlama-Adapters#960]
We have launched Pole Aggregator on Mainnet recently. It will be great if our aggregator can be included in Defi Llama.

Our website is in: https://pole.finance
Our app is in: https://app.pole.finance/

**Comment by 0xngmi** [comment]
we will need either:
- [Preferred] a script that calculates your TVL
- An API that returns your TVL (it must not include your staked governance tokens or pool2 when/if you launch a token)

**Comment by SyblePaul** [comment]
It will be hard to use the first method, since being an aggregator means all the TVL got deposited into the underlying pool.

**Comment by 0xngmi** [comment]
You don't have to use getToken queries, any kind of script will work (eg: I see that on your page you make multiple queries to https://solana-api.projectserum.com/ that calculate your TVL, using the exact same script here would be fine)

**Comment by SyblePaul** [comment]
I see, this makes sense. I will need to add: https://www.npmjs.com/package/@port.finance/port-sdk as dependency for this.

**Comment by SyblePaul** [comment]
See here: https://github.com/DefiLlama/DefiLlama-Adapters/pull/1004 @0xngmi

**Comment by 0xngmi** [comment]
merged, ty for the pr
