### ISSUE TITLE
Yieldly TVL suddenly went to 0

### ISSUE THREAD

**Issue by ejbaran** [DefiLlama/DefiLlama-Adapters#964]
The Yieldly TVL on Algorand suddenly went to 0 in the past 24 hours, while the Yieldly website provides TVL of over $100 million: https://app.yieldly.finance/

Yieldly adaptor
https://github.com/DefiLlama/DefiLlama-Adapters/blob/main/projects/yieldly/index.js

**Comment by ejbaran** [comment]
@AronTurner

**Comment by AronTurner** [comment]
@0xngmi i have changed the exported modules to mirror Pancakeswaps as seperate NLL TVL from staking TVL as per your requests, the modules were outputting the correct values last I checked but I assume since the schema has changed slightly the frontend may need an update?

**Comment by 0xngmi** [comment]
I've fixed it, the format of the PR was incorrect
