### ISSUE TITLE
Missing volume about APX Finance of BSC/Arbitrum/Base

### ISSUE THREAD

**Issue by bryansniyve** [DefiLlama/DefiLlama-Adapters#9652]
Could you help me to figure out what's wrong with our code or something weird of your data ?
```
DefiLlama-Adapters: projects/apollox/index.js
dimension-adapters: dexs/apollox/index.ts
```
<img width="2560" alt="截屏2024-04-02 14 33 47" src="https://github.com/DefiLlama/DefiLlama-Adapters/assets/134277602/d2bc375f-9932-492a-a1b4-0dfd057f1b3a">
<img width="2554" alt="截屏2024-04-02 14 34 15" src="https://github.com/DefiLlama/DefiLlama-Adapters/assets/134277602/5a78ce35-9cf8-497d-87ae-7e1d3d1030fd">
<img width="2559" alt="截屏2024-04-02 14 34 43" src="https://github.com/DefiLlama/DefiLlama-Adapters/assets/134277602/3d99284c-0435-42a6-b51a-78dd5f36c251">

We find that there were no volume data on this address: https://defillama.com/protocols/Derivatives of BSC/Arbitrum/Base chain

which path is: DeFi / Categories / Derivatives. 

But volume data work well in this address: https://defillama.com/derivatives 

which path is: Volumes / Derivatives.

<img width="2534" alt="截屏2024-04-02 14 37 34" src="https://github.com/DefiLlama/DefiLlama-Adapters/assets/134277602/adae2e6f-0f6c-41e5-95ae-89677317ab2f">
<img width="2535" alt="截屏2024-04-02 14 38 05" src="https://github.com/DefiLlama/DefiLlama-Adapters/assets/134277602/a8f67784-d548-48d0-bc6a-bb7f92a59e02">
<img width="2331" alt="截屏2024-04-02 14 38 35" src="https://github.com/DefiLlama/DefiLlama-Adapters/assets/134277602/719af11e-ad86-4c3a-88e1-257eced9d1b7">

**Comment by Define101** [comment]
@bryansniyve thanks for the report. We are look into

**Comment by realdealshaman** [comment]
has since been added
