### ISSUE TITLE
chian Rangers count protocol error

### ISSUE THREAD

**Issue by FlyingLittleBear** [DefiLlama/DefiLlama-Adapters#9728]
Our chain rangers has two protocols on DefiLlama:
(1)ponytaswap: https://defillama.com/protocol/ponytaswap
(2)rangers bridge:https://defillama.com/protocol/rangers-bridge?denomination=USD. 

But we can only see one protocol on the rangers chain dashborad:
https://defillama.com/chain/Rangers?volume=true&price=true&tvl=false&staking=false&pool2=false&govtokens=false&borrowed=false&doublecounted=false&liquidstaking=false&vesting=false
And the data i got by api is the same. It only contains ponytaswap's tvl.

How can i add protocol  rangers bridge to the chain rangers count?

**Comment by g1nt0ki** [comment]
hi, we dont count bridge tvl as part of any chain: https://github.com/DefiLlama/DefiLlama-Adapters/discussions/435
