### ISSUE TITLE
Wrong borrowed data for RMM V3

### ISSUE THREAD

**Issue by quangchuc** [DefiLlama/DefiLlama-Adapters#9763]
On the RMM V3, the correct total borrows are 3.96 M.
However, on DefiLlama, it shows that the borrowed amount is 15.14 M.
https://defillama.com/protocol/realt-rmm-marketplace-v2#information

Here is the protocol page: 
https://rmm.realtoken.network/markets/

Here is the address of RmmProtocolDataProvider to get data about each token pool: https://gnosisscan.io/address/0x11b45acc19656c6c52f93d8034912083ac7dd756#readContract

Token addresses: 
WXDAI: 0xe91D153E0b41518A2Ce8Dd3D7944Fa863463a97d
USDC: 0xDDAfbb505ad214D7b80b1f830fcCc89B60fb7A83
RTW (Wrapped RealTokens): 0xd3DFf217818b4F33eB38a243158FBeD2BBB029D3

**Comment by g1nt0ki** [comment]
hi @quangchuc it was 0xd3dff217818b4f33eb38a243158fbed2bbb029d3 'RTW-USD-01'
Once I removed the oracle, this issue went away
