### ISSUE TITLE
Tranchess TVL on Scroll Excluded b/c "Both Liquid Staking and Double Count toggles off"

### ISSUE THREAD

**Issue by bill-clippy** [DefiLlama/DefiLlama-Adapters#9900]
We noticed an issue following the integration of Tranchess Scroll TVL in #9868. On the [Scroll chain page](https://defillama.com/chain/Scroll), it appears that our TVL might be inaccurately excluded from the overall Scroll TVL due to potential double-counting.
 We'd like to clarify that our reported TVL includes assets that are native to the Scroll chain, specifically STONE token. These assets are not counted in any other protocol TVL. Could anyone help to include our TVL in Scroll’s total calculation?

Thank you for your assistance!

**Comment by g1nt0ki** [comment]
hi, you have two products, 

Tranchess yield - isnt this tokenizing yeild similar to pendle? if so, this category defaults to doublecounted
Tranchess Liquid - LSD tvl is by default not included in chain tvl

**Comment by bill-clippy** [comment]
I see, thanks for pointing it out!
