### ISSUE TITLE
Seamless TVL is no longer including wrapped tokens

### ISSUE THREAD

**Issue by fredwes** [DefiLlama/DefiLlama-Adapters#9961]
A fix was applied related to this PR https://github.com/DefiLlama/DefiLlama-Adapters/pull/9695 by @g1nt0ki to account for wrapped tokens supplied to Seamless markets. But recently this stopped working as of April 19th.

<img width="696" alt="Screenshot 2024-04-23 at 4 14 58 PM" src="https://github.com/DefiLlama/DefiLlama-Adapters/assets/6827305/6b5c9468-a870-4995-a8dc-06f6fc55fe06">

**Comment by g1nt0ki** [comment]
hi @fredwes there was a bug caused by token supply being 0, fixed it here: https://github.com/DefiLlama/defillama-server/commit/f6d4b2236833ae5de96304d444fc5511a77f6d8a
